import test from 'node:test';import assert from 'node:assert/strict';
import {runtime,life,step} from './harness.mjs';const api=runtime();
function setup(ids,kind='dummy',seed=93){const x=life(api,seed),{sim,p,room}=x;room.waveAt=100000;room.actors=[];const target=sim.actor(kind,0,-37);target.cooldown=10000;target.hp=target.hpMax=500;room.actors=[target];Object.assign(p,{x:0,z:-38,dir:0,stamina:100,staminaCap:100,autoFight:target.id});for(const id of ids)sim.learn(p,id);p.phaseWeights=[0,1,2].map(b=>Object.fromEntries(ids.filter(id=>api.skillById(id).band===b).map(id=>[id,100])));return {...x,target};}
function exchange(ids,kind='crawler'){const {sim,p,target}=setup(ids,kind);let started=false;for(let i=0;i<400;i++){sim.tick(1/30);if(p.combo)started=true;if(started&&!p.combo)break;}return {damage:500-target.hp,elapsed:sim.time,connections:sim.events.filter(e=>e.type==='skillconnection'),skills:sim.events.filter(e=>e.type==='skill'),charges:sim.events.filter(e=>e.type==='charge'),p,target};}
test('three phases run through contact auto combat and real ending/starting states',()=>{const r=exchange([60000,60001,60002]);assert.equal(r.skills.length,3);assert.ok(r.connections.length>=1);assert.ok(r.p.skillLife.connections['60000:60001']>0);});
test('compatible setup changes timing, not the skill definition or a generic power multiplier',()=>{const linked=exchange([60000,60001]),unlinked=exchange([60010,60001]);assert.ok(linked.connections.length>unlinked.connections.length);assert.ok(linked.charges[1].duration<unlinked.charges[1].duration);assert.equal(api.skillById(60001).power,.48);});
test('miss, wrong target, expired state or same phase never connects',()=>{const def=api.BL_SKILL_CATALOG.byId.get(60001),link={id:60000,target:'e',until:5,band:0,tags:['offbalance']};assert.ok(api.BloodlineSkills.connection(def,link,'e',4,1));for(const [target,time,band] of [['other',4,1],['e',6,1],['e',4,0]])assert.equal(api.BloodlineSkills.connection(def,link,target,time,band),false);const {sim,p,room}=setup([60000]);room.actors=[];sim.performStrike(p,room,api.skillById(60000));assert.ok(!p.skillExit);});
test('hit event alone cannot prematurely produce ending state; action must finish',()=>{const {sim,p,target,room}=setup([60000,60001]);p.currentSkill=60000;p.combo={band:0,total:1};sim.performStrike(p,room,api.skillById(60000));assert.ok(!p.skillLink);assert.equal(p.skillExit.target,target.id);api.SkillSystem.complete(sim,p);assert.equal(p.skillLink.target,target.id);});
test('a recovered target cannot be connected as offbalance',()=>{const {sim,p,target}=setup([60001]);target.stun=0;target.exposedUntil=0;p.combo={band:1,total:0};p.skillLink={id:60000,target:target.id,until:99,band:0,tags:['offbalance']};target.kind='crawler';assert.equal(api.SkillSystem.prepareCast(sim,p,api.skillById(60001)).linked,undefined);});
test('failed spend produces no connection or stale cast; wounded player loses connection',()=>{const {sim,p,target}=setup([60001]);Object.assign(p,{stamina:0,combo:{band:1,total:0},skillLink:{id:60000,target:target.id,until:99,band:0,tags:['offbalance']}});assert.equal(sim.beginComboStrike(p,60001),false);assert.ok(!p.skillCast);assert.ok(!sim.events.some(e=>e.type==='skillconnection'));p.stamina=100;sim.inflictWound(p,'rightArm','light',target);assert.ok(!p.skillLink);});
test('cost and recovery connection effects are local and survive only the active cast',()=>{const {sim,p,target}=setup([60012]);p.combo={band:2,total:0};p.skillLink={id:60011,target:target.id,until:99,band:1,tags:['rhythm']};const base=api.skillById(60012),before=JSON.stringify(base);const cast=api.SkillSystem.prepareCast(sim,p,base);assert.ok(cast.cost<base.cost);assert.ok(cast.recovery<base.recovery);assert.equal(JSON.stringify(base),before);sim.finishCombo(p);assert.ok(!p.skillCast);assert.ok(!p.skillLink);});
test('new hit occurs after charge and visible swing, never on discovery',()=>{const {sim,p}=setup([60000]);p.autoFight=null;p.combo={band:0,total:0};const seq=sim.seq;assert.ok(sim.beginComboStrike(p,60000));assert.equal(sim.events.filter(e=>e.seq>seq&&e.type==='hit').length,0);step(sim,1.2);assert.ok(sim.events.some(e=>e.seq>seq&&e.type==='hit'&&e.skill===60000));});
test('guard-break uses existing boss seals and victory rules',()=>{const {sim,p}=life(api),front=sim.makeRoom('front');front.stage=5;front.partySize=1;front.quota=999;const boss=sim.actor('boss',0,0);boss.cooldown=10000;front.actors=[boss];p.room=front.id;p.x=0;p.z=-1;p.dir=0;p.currentSkill=60002;const seals=[];for(let i=0;i<4;i++){sim.performStrike(p,front,api.skillById(60002));seals.push(boss.seals);sim.time+=1;}assert.deepEqual(seals,[3,2,1,0]);assert.equal(boss.alive,false);assert.ok(p.victory);});
test('movement, rest, age, stamina and pickup/equipment restrictions match base develop',()=>{const base=runtime(true),a=life(base,7),b=life(api,7);for(const v of [a,b]){v.p.age=4;v.p.x=0;v.p.z=6;v.room.actors=[];v.room.waveAt=9999;v.sim.command(v.p.id,{type:'move',x:1,z:0});step(v.sim,2);v.sim.command(v.p.id,{type:'sit',active:true});step(v.sim,3);}for(const k of ['x','z','age','ageFraction','enduranceXP','stamina','staminaCap','health','seated'])assert.equal(a.p[k],b.p[k],k);assert.ok(b.sim.receiveItem(b.p,'bell'));assert.ok(b.sim.receiveItem(b.p,'stone'));assert.equal(b.sim.receiveItem(b.p,'feather'),false);const rack=b.room.map.schools.find(a=>a.id==='armory');b.p.x=rack.x;b.p.z=rack.z+3;assert.equal(b.sim.command(b.p.id,{type:'equip',slot:'weapon',value:0}),false);b.p.age=7;assert.ok(b.sim.command(b.p.id,{type:'equip',slot:'weapon',value:0}));b.p.wounds.rightArm={severity:'lost'};assert.ok(api.skillRestriction(b.p,api.skillById(60000)));});
