import fs from 'node:fs/promises';
import path from 'node:path';
import {compileCatalog} from './tools/skill-catalog.mjs';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {buildInfo} from './deploy/build-info.mjs';
import {liveBuild} from './tools/archive-simulation.mjs';
import {LiveContract} from './src/live/contract.mjs';
import {buildLineage} from './tools/build-lineage.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const release=JSON.parse(await fs.readFile(path.join(root,'deploy/release.json'),'utf8'));
const environment=process.env.BLOODLINE_BUILD_ENV || 'local';
let commit=process.env.BLOODLINE_BUILD_COMMIT;
if (!commit) { try { commit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim(); } catch { commit='local-recovery'; } }
const info=buildInfo(release.baseVersion,environment,commit);
const live={...LiveContract,...await liveBuild(root)};
const assets={};for(const name of ['character/young-human-male-cm01.glb','golden-surfaces.png','village-kit.glb','material-atlas.png','detail-atlas.png','parchment.png','cloth-panel.png'])assets[name]=(await fs.readFile(path.join(root,'public/assets',name))).toString('base64');
const musicCatalog=JSON.parse(await fs.readFile(path.join(root,'public/assets/music/manifest.json'),'utf8')),musicAssets={};
for(const track of musicCatalog.tracks)musicAssets[track.id]=(await fs.readFile(path.join(root,'public/assets/music',track.file))).toString('base64');
const order=['live/contract.mjs','live/client.js','legacy/dialogue.js','legacy/core.js','skills/engine.js','skills/runtime.js','legacy/render_math.js','legacy/motion.js','legacy/art.js','render/tilt-shift.js','render/shaders.js','render/renderer-base.js','legacy/audio.js','legacy/labels.js','ui/presentation.js','ui/lineage/theatre.js','ui/lineage.js','ui/talk-fan.js','legacy/ui.js','ui/building-labels.js','render/motion-interpolation.js','legacy/game.js','assets/loader.js','world/environment.js','world/golden-slice.js','weather/weather.js','character/rig.js','character/golden-master.runtime.js','character/traveler-model.js','character/traveler-runtime.js','render/combat-presentation.js','render/adapter.js','audio/ambience.js','audio/score.js','skills/presentation.js','bootstrap.js'];
const skillDefinitions=compileCatalog(JSON.parse(await fs.readFile(path.join(root,'src/skills/catalog-source.json'),'utf8')));
const lineage=await buildLineage(root);
let code=`const LIVE_BUILD=Object.freeze(${JSON.stringify(live)});\nconst LINEAGE_VIEW=${JSON.stringify(lineage.data)};\nconst BUILD_INFO=Object.freeze(${JSON.stringify(info)});\nconst BL_SKILL_DEFINITIONS=${JSON.stringify(skillDefinitions)};\nconst VISUAL_ASSETS=${JSON.stringify(assets)};\n`;
code+=`const MUSIC_CATALOG=${JSON.stringify(musicCatalog)};\nconst MUSIC_ASSETS=${JSON.stringify(musicAssets)};\n`;
order.splice(order.indexOf('render/combat-presentation.js'),0,'render/skill-silk.js','render/skill-arcane.js','render/skill-effects.js');
for(const file of order)code+=`\n// SOURCE MODULE: ${file}\n`+(await fs.readFile(path.join(root,'src',file),'utf8')).replace(/^export /gm,'')+'\n';
let style=(await fs.readFile(path.join(root,'src/ui/base.css'),'utf8'))+'\n'+await fs.readFile(path.join(root,'src/ui/world-skin.css'),'utf8');
style+='\n'+await fs.readFile(path.join(root,'src/skills/skills.css'),'utf8');
style+='\n'+await fs.readFile(path.join(root,'src/ui/interaction.css'),'utf8')+'\n'+await fs.readFile(path.join(root,'src/ui/lineage.css'),'utf8');
style+='\n'+await fs.readFile(path.join(root,'src/ui/talk-fan.css'),'utf8');
style+='\n'+await fs.readFile(path.join(root,'src/ui/bequest.css'),'utf8');
style+='\n'+await fs.readFile(path.join(root,'src/live/update.css'),'utf8');
style+='\n'+await fs.readFile(path.join(root,'src/ui/skills-panel.css'),'utf8')+'\n'+await fs.readFile(path.join(root,'src/ui/wardrobe-panel.css'),'utf8')+'\n'+lineage.fontCSS;
style+='\n'+await fs.readFile(path.join(root,'src/ui/diorama-materials.css'),'utf8');
style=style.replace(/asset:([a-z-]+\.png)/g,(_,name)=>`data:image/png;base64,${assets[name]}`);
let html=await fs.readFile(path.join(root,'src/shell.html'),'utf8');html=html.replace('/*__STYLE__*/',style).replace('/*__SCRIPT__*/',`'use strict';\n(async()=>{\n${code}\n})();`.replace(/<\/script/gi,'<\\/script'));
await fs.mkdir(path.join(root,'dist'),{recursive:true});await fs.writeFile(path.join(root,'dist/index.html'),html);await fs.writeFile(path.join(root,'dist/source-manifest.json'),JSON.stringify({name:'血脈の系譜',visualBuild:'VS-01',simulationVersion:'0.6.0',modules:order,assets:Object.keys(assets)},null,2));console.log('Built '+Buffer.byteLength(html)+' bytes from '+order.length+' source modules');
