/* Renderer adapter: keeps the existing camera/input contract and draw ordering.
 * Everything here consumes snapshots; none of it calls Simulation commands. */
class SliceRenderer extends Renderer{
 constructor(canvas,size=null){super(canvas,size);this.weather=new WeatherState();this.weatherState=this.weather.sample(0);this.rigs=new RigRenderer(this);this.rainPass=new RainPass(this);this.combatPresentation=new CombatPresentation(this);this.goldenTex=this.textureFrom(AssetBank.images['golden-surfaces.png']);this.materialTex=this.textureFrom(AssetBank.images['material-atlas.png']);this.detailTex=this.textureFrom(AssetBank.images['detail-atlas.png']);const one=document.createElement('canvas');one.width=one.height=2;one.getContext('2d').fillRect(0,0,2,2);this.terrainTex=this.textureFrom(one);this.gpuExt=this.gl.getExtension('EXT_disjoint_timer_query_webgl2');this.gpuQueries=[];this.cpuSamples=[];this.frameSamples=[];this.weaponTips=new Map();this.lastWall=0;this.cpuMs=0;this.currentSnapshot=null;this.currentTime=0;this.shakeOffset=[0,0];this.art=new GoldenArt(this);}
 textureFrom(image){const gl=this.gl,t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t;}
 setupSurfaceUniforms(options={},program=this.program){const gl=this.gl,w=this.weatherState||this.weather.sample(0);if(this.terrainDirty&&this.terrainData){gl.deleteTexture(this.terrainTex);this.terrainTex=this.textureFrom(this.terrainData);this.terrainDirty=false;}
  for(const [i,name,tex]of [[0,'shadowTex',this.shadowStatic.tex],[1,'dynamicShadow',this.shadowDynamic.tex],[2,'materialAtlas',this.materialTex],[3,'detailAtlas',this.detailTex],[4,'terrainMap',this.terrainTex],[6,'goldenAtlas',this.goldenTex]]){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,tex);this.int(program,name,i);}
  this.uniform(program,'skyColor',w.sky);this.uniform(program,'groundColor',w.ground);this.uniform(program,'sunColor',w.sun);this.uniform(program,'fogColor',w.fog);this.uniform(program,'sunStrength',w.strength);this.uniform(program,'skyStrength',w.ambient);this.uniform(program,'wetness',w.wet);this.uniform(program,'fogDensity',w.density);this.uniform(program,'wind',w.wind);this.uniform(program,'terrainEnabled',this.sceneKey.startsWith('village')?1:0);
  const local=[...(this.art.sources||[])].sort((a,b)=>Math.hypot(a.x-this.camera.x,a.z-this.camera.z)-Math.hypot(b.x-this.camera.x,b.z-this.camera.z));
  const impact=this.effects.find(e=>this.currentTime-e.born<.10&&['hit','partbreak'].includes(e.type)&&Number.isFinite(e.x));if(impact)local.unshift({x:impact.x,y:1.2,z:impact.z,kind:'impact'});
  for(let i=0;i<4;i++){const s=local[i],active=i<(this.quality==='low'?1:this.quality==='medium'?2:4);this.uniform(program,'localPos'+i,s?[s.x,s.y,s.z]:[0,-100,0]);const flicker=s?.kind==='fire'?1+Math.sin(this.currentTime*13)*.07:1;this.uniform(program,'localColor'+i,s&&active?[s.kind==='impact'?6.0:4.2*flicker,s.kind==='impact'?3.5:1.70*flicker,.40*flicker]:[0,0,0]);}
 }
 put(type,m,c,surface=0,alpha=1,target=this.dynamic){if(this.rigs?.pending&&target===this.dynamic){this.rigs.capture(type,m,c,surface,alpha);if(type==='blade'){this.weaponTips.set(this.rigs.pending.p.id,[m[12]+m[4]*1.22,m[13]+m[5]*1.22,m[14]+m[6]*1.22]);}return;}super.put(type,m,c,surface,alpha,target);}
 drawBatches(map,program,shadow=false){super.drawBatches(map,program,shadow);if(map===this.dynamic)this.rigs?.draw(shadow);}
 geometry(type){const source=RG_CACHE.get(type);if(source?.dirty&&this.geo.has(type)){const g=this.geo.get(type),gl=this.gl,data=new Float32Array(source.count*6);for(let i=0;i<source.count;i++){data.set(source.positions.subarray(i*3,i*3+3),i*6);data.set(source.normals.subarray(i*3,i*3+3),i*6+3);}gl.bindBuffer(gl.ARRAY_BUFFER,g.vertex);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);g.count=source.count;source.dirty=false;return g;}const g=super.geometry(type);if(source)source.dirty=false;return g;}
 matrix(){const c=this.camera,aspect=this.width/this.height,sy=c.y??1;this.viewHeight=c.zoom/Math.min(1,aspect*.90);this.viewWidth=this.viewHeight*aspect;const shift=this.logicalSize?0:(this.panelShift||0),side=this.logicalSize?0:(this.panelShiftSide||0),x=c.x+Math.sin(c.yaw)*shift+Math.cos(c.yaw)*side+(this.logicalSize?0:this.shakeOffset[0]),z=c.z+Math.cos(c.yaw)*shift-Math.sin(c.yaw)*side+(this.logicalSize?0:this.shakeOffset[1]);this.viewCenter={x,z,y:sy};const target=[x,sy,z],d=38;this.eye=[x+Math.sin(c.yaw)*Math.cos(c.pitch)*d,sy+Math.sin(c.pitch)*d,z+Math.cos(c.yaw)*Math.cos(c.pitch)*d];this.view=rLookAt(this.eye,target);this.vp=rMultiply(rOrtho(-this.viewWidth/2,this.viewWidth/2,-this.viewHeight/2,this.viewHeight/2,.1,120),this.view);this.unitsToClip=2/Math.min(this.viewWidth,this.viewHeight);this.lightVP=rMultiply(rOrtho(-24,24,-24,24,.1,100),rLookAt([c.x-22,38,c.z+19],[c.x,0,c.z]));}
 combatFX(s,t){this.combatPresentation.update(s);}
 drawWeather(s){this.rainPass.draw(s);}
 cameraImpulse(s){let x=0,z=0;const p=s.player;if(!p)return[0,0];for(const e of this.effects){const own=e.source===p.id||e.target===p.id||e.player===p.id;if(!own||!['hit','wound','partbreak','blocked'].includes(e.type))continue;const u=(s.t-e.born)/.19;if(u<0||u>1)continue;const mag=(e.type==='partbreak'?.085:.035)*(1-u)**2;x+=Math.sin(u*24)*mag;z+=Math.cos(u*19)*mag*.7;}return[x,z];}
 render(s,dt=.016,options={}){if(!this.rigs)return super.render(s,dt,options);const start=performance.now();this.currentTime=s.t||0;this.currentSnapshot=s;this.weatherState=this.weather.sample(s.t||0,s.map?.seed||0,!!options.portrait||!!options.clan);this.weatherState.fogColor=this.weatherState.fog;this.rigs.active.length=0;this.weaponTips.clear();this.shakeOffset=this.cameraImpulse(s);let query=null;
  const gl=this.gl,ext=this.gpuExt;if(ext&&this.gpuQueries.length<4){query=gl.createQuery();gl.beginQuery(ext.TIME_ELAPSED_EXT,query);}
  super.render(s,dt,options);if(query){gl.endQuery(ext.TIME_ELAPSED_EXT);this.gpuQueries.push(query);}if(ext&&this.gpuQueries.length){const q=this.gpuQueries[0];if(gl.getQueryParameter(q,gl.QUERY_RESULT_AVAILABLE)){if(!gl.getParameter(ext.GPU_DISJOINT_EXT))this.gpuMs=gl.getQueryParameter(q,gl.QUERY_RESULT)/1e6;gl.deleteQuery(q);this.gpuQueries.shift();}}
  this.cpuMs=performance.now()-start;this.cpuSamples.push(this.cpuMs);if(this.cpuSamples.length>180)this.cpuSamples.shift();if(this.lastWall)this.frameSamples.push(start-this.lastWall);if(this.frameSamples.length>180)this.frameSamples.shift();this.lastWall=start;
  const pixels=this.canvas.width*this.canvas.height;Object.assign(this.stats,{cpuSubmitMs:+this.cpuMs.toFixed(2),gpuMs:this.gpuMs??null,frameMs:this.frameSamples.at(-1)||0,weather:this.weatherState.kind,quality:this.quality,textureMemoryEstimateMiB:+((pixels*12+(this.stats.dofBytes||0)+3*512*512*4*1.333+768*768*4*1.333+(1536*1536+1024*1024)*4)/1048576).toFixed(2),jsHeapMiB:performance.memory?+(performance.memory.usedJSHeapSize/1048576).toFixed(2):null,renderer:'WebGL2 / metallic-roughness / GPU bone palette',rigCount:this.rigs.records.size});
 }
}
