import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),base='10fb501e635f953c529dfbfc6898d8c0fd21e66c';
const html=await fs.readFile(path.join(root,'dist/index.html'),'utf8');let code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const boot=code.indexOf('// SOURCE MODULE: bootstrap.js');if(boot<0)throw Error('Missing build bootstrap');
code=code.slice(0,boot).replace(/^const MUSIC_ASSETS=.*;$/m,'const MUSIC_ASSETS={};')+(await fs.readFile(path.join(root,'tools/enemies/review-scenes.js'),'utf8'))+'\n'+(await fs.readFile(path.join(root,'tools/enemies/review-runtime.js'),'utf8')).replace('__BASE_SHA__',base)+'\n})();';new vm.Script(code);
const shell=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>血脈の系譜 — 敵図鑑とモーション</title><style>
*{box-sizing:border-box}body{margin:0;background:#30392f;color:#ede3ca;font:14px system-ui;display:flex;flex-direction:column;height:100dvh}header,footer{padding:9px 12px;display:flex;gap:9px;flex-wrap:wrap;align-items:center}h1{font-size:16px;margin:0}main{flex:1;min-height:190px;position:relative;overflow:hidden}canvas{display:block;width:100%;height:100%}.caption{position:absolute;left:14px;top:12px;pointer-events:none;text-shadow:0 1px 5px #20291e}.caption strong{display:block;font-size:19px}.caption output{display:block;font-size:13px;margin-top:4px;color:#fff0b7}label{display:flex;align-items:center;gap:5px}select,button{font:inherit;color:inherit;background:#4c5544;border:1px solid #a59570;padding:9px;border-radius:5px;min-height:42px}button{cursor:pointer}button:focus-visible,select:focus-visible{outline:2px solid #e5c977}input{accent-color:#d5b975}#status{font-size:10px;opacity:.75}small{font-size:11px;opacity:.8}#seek{flex:1;min-width:90px}#vitality{flex:1;min-width:90px;max-width:230px}#vitality-value{min-width:3.5em;font-variant-numeric:tabular-nums}#vitality-help{width:100%}.vitality-row{width:100%}.row{display:flex;align-items:center;gap:8px;flex-wrap:wrap;width:100%}.enemy-select{flex:1}.enemy-select select{width:100%;min-width:130px}details{width:100%;font-size:12px}summary{padding:6px 0;cursor:pointer}details .row{margin-top:7px}#pose{max-width:170px}footer{padding-bottom:max(10px,env(safe-area-inset-bottom))}@media(min-width:800px){footer{justify-content:center}.row{width:auto}details{max-width:1000px}main{min-height:350px}}@media(max-height:520px){header{display:none}footer{padding:4px 8px;gap:4px}.row{width:auto}main{min-height:140px}small{display:none}}
</style><header><h1>血脈の系譜 · 敵図鑑</h1><output id="status" role="status">準備中…</output></header><main><canvas id="world"></canvas><div class="caption"><strong id="enemy-name"></strong><output id="phase" aria-live="polite">モーションを準備中…</output></div></main><footer>
<div class="row"><button id="prev" aria-label="前の敵">◀</button><label class="enemy-select"><select id="form" aria-label="敵の種類"><option value="all">系統を混ぜる</option></select></label><button id="next" aria-label="次の敵">▶</button></div>
<div class="row"><label>動作<select id="pose"><option value="sequence">一通り再生</option><option value="attack">予兆 → 攻撃</option><option value="run">移動</option><option value="idle">待機</option><option value="guard">防御</option><option value="hit">被弾</option><option value="death">死亡</option></select></label><button id="pause">⏸ 停止</button><button id="replay">最初から</button></div>
<div class="row vitality-row"><label for="vitality">生命力</label><input id="vitality" type="range" min="0" max="100" step="1" value="100" aria-describedby="vitality-help"><output id="vitality-value" for="vitality">100%</output><label>部位破壊<select id="broken-part"><option value="none">なし</option><option value="rightArm">右腕・前脚</option><option value="leftArm">左腕・前脚</option><option value="rightLeg">右脚・後脚</option><option value="leftLeg">左脚・後脚</option><option value="bothLegs">両脚・後脚</option><option value="bothArms">両腕・前脚</option><option value="rightArmLeftLeg">右腕＋左脚</option></select></label></div>
<small id="vitality-help">生命力を下げると消耗・瀕死の動きに。両脚破壊＋「移動」で這いずりを確認できます。</small>
<div class="row"><input id="seek" aria-label="再生位置（操作すると一時停止）" type="range" min="0" max="999" value="0"><small>位置を動かすと停止。▶ 再生で再開。</small></div>
<details><summary>比較・視点・負荷の設定</summary><div class="row"><label>表示<select id="version"><option value="after">改善後</option><option value="before">従来の同系統</option></select></label><label>数<select id="count"><option>1</option><option>2</option><option>8</option><option>24</option></select></label><label>品質<select id="quality"><option value="medium">中</option><option value="low">低</option><option value="high">高</option></select></label><label>視点<select id="angle"><option value=".32">斜め</option><option value="0">正面</option><option value="1.57">横</option><option value="3.14">背面</option></select></label><label>速度<select id="speed"><option value="1">通常</option><option value=".25">¼</option></select></label><button id="measure">40秒測定・JSON保存</button></div><small>本編のモデル・描画エンジンを使用。セーブは作りません。測定は準備10秒＋10秒×3回。実戦での確認も必要です。</small></details>
</footer><script>__CODE__</script></html>`;
const target=path.join(root,'dist/Bloodline_Legacy_Enemy_Review.html');await fs.writeFile(target,shell.replace('__CODE__',()=>code.replace(/<\/script/gi,'<\\/script')));console.log(target);
