


/* Self-contained WebGL 2 renderer. Shared meshes, spatial visibility, shadow maps and
   screen-space contact shading. No downloaded models or generated picture backdrops. */
const RVERT=`#version 300 es
precision highp float;
layout(location=0) in vec3 pos;layout(location=1) in vec3 nor;
layout(location=2) in mat4 model;layout(location=6) in vec4 ink;layout(location=7) in float surface;
uniform mat4 vp;uniform mat4 lightVP;
out vec3 vWorld;out vec3 vNormal;out vec4 vInk;out float vSurface;out vec4 vShadow;out vec3 vLocal;
void main(){vec4 w=model*vec4(pos,1.);vWorld=w.xyz;vNormal=normalize(mat3(model)*(nor/vec3(dot(model[0].xyz,model[0].xyz),dot(model[1].xyz,model[1].xyz),dot(model[2].xyz,model[2].xyz))));vInk=ink;vSurface=surface;vShadow=lightVP*w;vLocal=pos;gl_Position=vp*w;}`;
const RFRAG=`#version 300 es
precision highp float;
in vec3 vWorld;in vec3 vNormal;in vec4 vInk;in float vSurface;in vec4 vShadow;in vec3 vLocal;
uniform sampler2D shadowTex;uniform sampler2D dynamicShadow;uniform vec3 eye;uniform float time;uniform bool shadows;uniform vec2 focus;
layout(location=0) out vec4 outColor;layout(location=1) out vec4 outNormal;
float hash(vec3 p){p=fract(p*.3183099+vec3(.17,.11,.43));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float shadowValue(sampler2D map,vec3 p,float bias){float oc=0.;vec2 texel=1./vec2(textureSize(map,0));for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=texture(map,p.xy+vec2(x,y)*texel*4.25).r;oc+=p.z-bias>d?1.:0.;}return oc/9.;}
void main(){vec3 N=normalize(vNormal),L=normalize(vec3(-.48,.85,.42)),V=normalize(eye-vWorld);vec3 base=vInk.rgb;float alpha=vInk.a;float surf=vSurface;
 if(surf>1.5&&surf<2.5){float d=length(vLocal.xz);alpha*=pow(max(0.,1.-d),2.1);if(alpha<.003)discard;outColor=vec4(base,alpha);outNormal=vec4(.5,1.,.5,0.);return;}
 // Fiber detail is derivative filtered so distant roofs do not shimmer.
 float aa=clamp(1.-length(fwidth(vWorld))*3.7,0.,1.);float grain=(hash(floor(vWorld*160.))-.5)*.025*aa;
 if(surf<.5){float stitch=sin(vWorld.x*148.+vWorld.y*97.)*sin(vWorld.z*137.-vWorld.y*91.);base*=1.+grain*.35+stitch*.003*aa;}
 if(surf>7.5&&surf<8.5){float wood=sin(vWorld.y*72.+sin(vWorld.x*3.)*3.+vWorld.z*8.);base*=1.+wood*.012*aa+grain*.35;}
 if(surf>8.5&&surf<9.5)base*=1.+grain*.8;
 if(surf>11.5){float grass=sin(vWorld.x*18.+vWorld.z*12.)*sin(vWorld.x*8.-vWorld.z*17.);base*=1.+grass*.002*aa;}
 if(surf>.5&&surf<1.5){float wave=sin(vWorld.x*1.8+time*.6)*cos(vWorld.z*1.5-time*.45);base+=vec3(.02,.028,.026)*wave;N=normalize(N+vec3(sin(vWorld.z*2.+time)*.06,0.,cos(vWorld.x*2.+time)*.06));}
 float diff=max(0.,dot(N,L));float shade=0.;if(shadows&&surf<3.5||shadows&&surf>7.5){vec3 s=vShadow.xyz/vShadow.w*.5+.5;if(all(greaterThan(s,vec3(0.)))&&all(lessThan(s,vec3(1.)))){float bias=max(.0010,.0022*(1.-dot(N,L)));shade=max(shadowValue(shadowTex,s,bias),shadowValue(dynamicShadow,s,bias));}}
 vec3 sky=vec3(.84,.88,.86),ground=vec3(.66,.63,.54);vec3 hemi=mix(ground,sky,N.y*.5+.5);
 vec3 lit=base*(hemi*.60+vec3(1.0,.965,.89)*diff*(1.-shade*.55)*.46+vec3(.18,.18,.16));
 float rim=pow(1.-max(0.,dot(N,V)),2.2);if(surf<.5)lit+=base*rim*.075;
 if(surf>9.5&&surf<11.5){vec3 H=normalize(L+V);float sp=pow(max(0.,dot(N,H)),surf>10.5?52.:30.);lit+=vec3(1.,.94,.78)*sp*.23*(1.-shade*.7);}
 if(surf>3.5&&surf<7.5)lit=base*(surf<4.5?1.10:1.);
 float fog=smoothstep(22.,58.,length(vWorld.xz-focus));lit=mix(lit,vec3(.92,.89,.81),fog*.57);
 outColor=vec4(lit,alpha);outNormal=vec4(N*.5+.5,1.);
}`;
const RDEPTH=`#version 300 es
precision highp float;void main(){}`;
const RPOSTV=`#version 300 es
precision highp float;out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.-1.,0.,1.);}`;
const RPOSTF=`#version 300 es
precision highp float;in vec2 uv;out vec4 color;uniform sampler2D image;uniform sampler2D depth;uniform sampler2D normals;uniform vec2 texel;uniform float occlusion;uniform float portrait;
void main(){vec3 c=texture(image,uv).rgb;float d=texture(depth,uv).r;vec3 n=texture(normals,uv).rgb*2.-1.;float occ=0.;
 if(d<.9999&&occlusion>.1){for(int k=0;k<12;k++){float a=float(k)*2.399963;float r=3.+float(k%4)*3.;vec2 off=vec2(cos(a),sin(a))*r*texel;float q=texture(depth,uv+off).r;float delta=d-q;occ+=smoothstep(.00045,.003,delta)*(1.-smoothstep(.006,.021,delta));}occ/=12.;}
 c*=1.-occ*.31*occlusion;
 // A small five-tap luma-guided edge filter, never a blur over the world.
 vec3 a=texture(image,uv+vec2(texel.x,0.)).rgb,b=texture(image,uv-vec2(texel.x,0.)).rgb,e=texture(image,uv+vec2(0.,texel.y)).rgb,f=texture(image,uv-vec2(0.,texel.y)).rgb;vec3 l=vec3(.299,.587,.114);float lo=min(min(dot(a,l),dot(b,l)),min(dot(e,l),dot(f,l))),hi=max(max(dot(a,l),dot(b,l)),max(dot(e,l),dot(f,l)));float edge=smoothstep(.10,.32,hi-lo);c=mix(c,(a+b+e+f+c*4.)/8.,edge*.34);
 c=mix(c,pow(max(c,vec3(0.)),vec3(.91)),.30);float vignette=1.-dot(uv-.5,uv-.5)*.075*(1.-portrait);c*=vignette;color=vec4(c,portrait>1.5?(d<.9999?1.:0.):1.);
}`;
class Renderer{
 constructor(canvas,size=null){this.canvas=canvas;this.logicalSize=size;this.gl=canvas.getContext('webgl2',{alpha:!!size,antialias:false,powerPreference:'high-performance',preserveDrawingBuffer:true});if(!this.gl)throw new Error('WebGL 2 を利用できません。Chromeで開いてください。');this.frame=0;this.stats={};this.lost=false;this.camera={x:0,z:5,zoom:16.8,yaw:.42,pitch:.68};this.quality='auto';this.scale=1;this.static=new Map();this.dynamic=new Map();this.fxBatches=new Map();this.impactFX=new Map();this.groundFX=new Map();this.geo=new Map();this.labels=[];this.effects=[];this.art=new ArtDirector(this);this.sceneKey='';this.staticShadowDirty=true;this.lastShadow=[1e9,1e9];this.program=this.programOf(RVERT,RFRAG);this.depthProgram=this.programOf(RVERT,RDEPTH);this.post=this.programOf(RPOSTV,RPOSTF);this.shadowStatic=this.shadowTarget(1536);this.shadowDynamic=this.shadowTarget(1024);this.lastSize='';this.resize();this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;});this.canvas.addEventListener('webglcontextrestored',()=>location.reload());this.frameMs=16;this.stableFrames=0;}
 programOf(v,f){const gl=this.gl;const shader=(type,text)=>{const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;};const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));p.u=new Map();return p;}
 uniform(p,name,value){const gl=this.gl;let u=p.u.get(name);if(u===undefined){u=gl.getUniformLocation(p,name);p.u.set(name,u);}if(u===null)return;if(value instanceof Float32Array&&value.length===16)gl.uniformMatrix4fv(u,false,value);else if(Array.isArray(value)){if(value.length===2)gl.uniform2fv(u,value);else if(value.length===3)gl.uniform3fv(u,value);}else gl.uniform1f(u,value);}
 int(p,name,v){let u=p.u.get(name);if(u===undefined){u=this.gl.getUniformLocation(p,name);p.u.set(name,u);}if(u!==null)this.gl.uniform1i(u,v);}
 shadowTarget(size){const gl=this.gl,tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,size,size,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);const fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,tex,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error('影バッファを確保できません');gl.clearDepth(1);gl.clear(gl.DEPTH_BUFFER_BIT);gl.bindFramebuffer(gl.FRAMEBUFFER,null);return{fb,tex,size};}
 resize(){const gl=this.gl,w=this.logicalSize?.width||this.canvas.clientWidth||innerWidth,h=this.logicalSize?.height||this.canvas.clientHeight||innerHeight;const dpr=Math.min(devicePixelRatio||1,this.quality==='high'?1.65:1.35)*this.scale,ww=Math.round(w*dpr),hh=Math.round(h*dpr);const key=ww+'x'+hh;if(key===this.lastSize)return;this.lastSize=key;this.canvas.width=ww;this.canvas.height=hh;this.width=w;this.height=h;if(this.target){gl.deleteFramebuffer(this.target.fb);for(const t of [this.target.image,this.target.normals,this.target.depth])gl.deleteTexture(t);}
 const tex=(depth=false)=>{const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,depth?gl.DEPTH_COMPONENT24:gl.RGBA8,ww,hh,0,depth?gl.DEPTH_COMPONENT:gl.RGBA,depth?gl.UNSIGNED_INT:gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,depth?gl.NEAREST:gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,depth?gl.NEAREST:gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t;};const fb=gl.createFramebuffer(),image=tex(),normals=tex(),depth=tex(true);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,image,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT1,gl.TEXTURE_2D,normals,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,depth,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0,gl.COLOR_ATTACHMENT1]);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error('描画バッファを確保できません');gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.target={fb,image,normals,depth};}
 setQuality(q){this.quality=q;this.scale=q==='low'?.75:1;this.lastSize='';this.resize();}
 put(type,m,c,surface=0,alpha=1,target=this.dynamic){let batch=target.get(type);if(!batch){batch=[];target.set(type,batch);}const col=Array.isArray(c)?c:rColor(c);batch.push([...m,col[0],col[1],col[2],alpha,surface]);}
 add(type,x,y,z,sx,sy,sz,c,yaw=0,rz=0,rx=0,surf=0,alpha=1,target=this.dynamic){this.put(type,rModel(x,y,z,sx,sy,sz,yaw,rz,rx),c,surf,alpha,target);}
 blob(x,z,sx,sz,a=.28,target=this.fxBatches){this.add('disk',x,.27,z,sx,1,sz,'#665b42',0,0,0,2,a,target);}
 geometry(type){if(this.geo.has(type))return this.geo.get(type);const gl=this.gl,g=rGeometry(type);if(!g.count)throw new Error('Unknown mesh: '+type);const vao=gl.createVertexArray();gl.bindVertexArray(vao);const data=new Float32Array(g.count*6);for(let i=0;i<g.count;i++){data.set(g.positions.subarray(i*3,i*3+3),i*6);data.set(g.normals.subarray(i*3,i*3+3),i*6+3);}const vertex=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vertex);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);for(let i=0;i<2;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,24,i*12);}const instance=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,instance);for(let i=0;i<4;i++){gl.enableVertexAttribArray(2+i);gl.vertexAttribPointer(2+i,4,gl.FLOAT,false,84,i*16);gl.vertexAttribDivisor(2+i,1);}gl.enableVertexAttribArray(6);gl.vertexAttribPointer(6,4,gl.FLOAT,false,84,64);gl.vertexAttribDivisor(6,1);gl.enableVertexAttribArray(7);gl.vertexAttribPointer(7,1,gl.FLOAT,false,84,80);gl.vertexAttribDivisor(7,1);gl.bindVertexArray(null);const out={...g,vao,vertex,instance};this.geo.set(type,out);return out;}
 visible(m,vp,padding=0){const x=m[12],y=m[13],z=m[14];const r=Math.max(Math.hypot(m[0],m[1],m[2]),Math.hypot(m[4],m[5],m[6]),Math.hypot(m[8],m[9],m[10]))*1.75;const clipX=vp[0]*x+vp[4]*y+vp[8]*z+vp[12],clipY=vp[1]*x+vp[5]*y+vp[9]*z+vp[13];return Math.abs(clipX)<1+r*this.unitsToClip+padding&&Math.abs(clipY)<1+r*this.unitsToClip+padding;}
 drawBatches(map,program,shadow=false){
  const gl=this.gl,buckets=new Map(),pixelScale=this.width/this.viewWidth;
  for(const [type,items] of map)for(const m of items){
   if(shadow&&(m[20]===1||m[20]===2||m[20]===4||m[19]<.85))continue;
   if(!this.visible(m,shadow?this.lightVP:this.vp,shadow?.4:.09))continue;
   const radius=Math.max(Math.hypot(m[0],m[1],m[2]),Math.hypot(m[4],m[5],m[6]),Math.hypot(m[8],m[9],m[10])),pixels=radius*pixelScale;
   let lod=type;if(type==='sphere'&&(pixels<11||shadow))lod='bead';else if(type==='rbox'&&(pixels<7||shadow&&radius<.65))lod='box';else if(type==='leaf'&&(pixels<7||shadow))lod='leaflow';
   if(lod!==type)this.stats.lodInstances++;
   if(!buckets.has(lod))buckets.set(lod,[]);buckets.get(lod).push(m);
  }
  for(const [type,rows]of buckets){const g=this.geometry(type),data=new Float32Array(rows.length*21);for(let i=0;i<rows.length;i++)data.set(rows[i],i*21);gl.bindVertexArray(g.vao);gl.bindBuffer(gl.ARRAY_BUFFER,g.instance);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);gl.drawArraysInstanced(gl.TRIANGLES,0,g.count,rows.length);this.stats.calls++;this.stats.triangles+=g.count/3*rows.length;if(!shadow)this.stats.instances+=rows.length;}
 }

 matrix(){const c=this.camera,aspect=this.width/this.height;this.viewHeight=c.zoom/Math.min(1,aspect*.90);this.viewWidth=this.viewHeight*aspect;const target=[c.x,1.0,c.z],distance=38,eye=[c.x+Math.sin(c.yaw)*Math.cos(c.pitch)*distance,1.0+Math.sin(c.pitch)*distance,c.z+Math.cos(c.yaw)*Math.cos(c.pitch)*distance];this.eye=eye;this.view=rLookAt(eye,target);this.vp=rMultiply(rOrtho(-this.viewWidth/2,this.viewWidth/2,-this.viewHeight/2,this.viewHeight/2,.1,120),this.view);this.unitsToClip=2/Math.min(this.viewWidth,this.viewHeight);const shadowCenter=[c.x,0,c.z],lightEye=[c.x-22,38,c.z+19];this.lightVP=rMultiply(rOrtho(-24,24,-24,24,.1,100),rLookAt(lightEye,shadowCenter));}
 screenToWorld(dx,dy){const y=this.camera.yaw,p=this.camera.pitch;return{x:Math.cos(y)*dx+Math.sin(y)*dy/Math.sin(p),z:-Math.sin(y)*dx+Math.cos(y)*dy/Math.sin(p)};}
 pointToWorld(x,y){const dx=(x/this.width-.5)*this.viewWidth,dy=(y/this.height-.5)*this.viewHeight;const v=this.screenToWorld(dx,dy);return{x:this.camera.x+v.x-Math.sin(this.camera.yaw)/Math.tan(this.camera.pitch),z:this.camera.z+v.z-Math.cos(this.camera.yaw)/Math.tan(this.camera.pitch)};}
 project(x,y,z){const m=this.vp;if(!m)return{x:-999,y:-999,visible:false};const xx=m[0]*x+m[4]*y+m[8]*z+m[12],yy=m[1]*x+m[5]*y+m[9]*z+m[13],zz=m[2]*x+m[6]*y+m[10]*z+m[14];return{x:(xx+1)*this.width/2,y:(1-yy)*this.height/2,visible:Math.abs(xx)<1.15&&Math.abs(yy)<1.15&&Math.abs(zz)<1};}
 effect(ev,t){if(['hit','wound','partbreak','blocked','guard','parry','skill','death','status','release','released','learn'].includes(ev.type)){this.effects.push({...ev,born:t,life:ev.type==='partbreak'?1.25:ev.type==='skill'?1.1:.8});if(this.effects.length>100)this.effects.splice(0,20);}}
 combatFX(snapshot,t){const entities=[...snapshot.players||[],...snapshot.actors||[]];if(snapshot.player&&!entities.some(x=>x.id===snapshot.player.id))entities.push(snapshot.player);const find=id=>entities.find(x=>x.id===id);for(const p of entities){if(p.alive===false)continue;const sk=skillById(p.pendingSkill?.id??p.attackSkill);const pt=t;
 if(p.autoFight){for(let j=0;j<10;j++){const a=t*.8+j*TAU/10,rad=1.3+(j%3)*.18;this.add('bead',p.x+Math.sin(a)*rad,.21+(j%3)*.07,p.z+Math.cos(a)*rad,.32,.13,.20,'#e9d9b8',a,0,0,0,.17+(j%2)*.07,this.fxBatches);}}
 if(p.telegraph){const q=p.telegraph,u=clamp((t-q.started)/Math.max(.05,q.at-q.started),0,1);this.add('sector:1.7',p.x,.28,p.z,2.3,1,2.3,'#be735d',q.dir??p.dir,0,0,4,.13+u*.19,this.fxBatches);this.add('ring:1.7',p.x,.29,p.z,2.3,1,2.3,'#bc806a',q.dir??p.dir,0,0,4,.42,this.fxBatches);}
 if(sk&&p.action==='attack'&&p.actionUntil>t){const u=clamp((pt-p.actionStarted)/Math.max(.01,p.actionUntil-p.actionStarted),0,1),beat=(u*(sk.hits||1))%1;if(beat>.18&&beat<.83){const a=p.dir+(beat-.43)*2.2,fade=Math.sin((beat-.18)/.65*Math.PI),size=sk.animation==='spin'?2.05:1.65;for(let k=0;k<3;k++)this.add('slash:2.7',p.x,.8+k*.15,p.z,size+k*.15,.4,size+k*.15,['#fff4ce','#edc983','#d8bd83'][k],a,0,k===2?.15:-.18,4,fade*(.62-k*.12),this.fxBatches);}}
 }
 this.effects=this.effects.filter(e=>t-e.born<e.life);for(const e of this.effects){const p=find(e.id||e.target||e.player),source=find(e.source);let x=Number.isFinite(e.x)?e.x:p?.x,z=Number.isFinite(e.z)?e.z:p?.z;if(x===undefined||z===undefined)continue;if(source&&p){const d=Math.hypot(source.x-p.x,source.z-p.z)||1;const off=p.elite?.62:.32;x+=(source.x-p.x)/d*off;z+=(source.z-p.z)/d*off;}const age=t-e.born,u=clamp(age/e.life,0,1);if(e.type==='skill'||e.type==='death'||e.type==='released'||e.type==='release')continue;const broken=e.type==='partbreak',hit=['hit','wound','blocked','parry','guard'].includes(e.type),palette=e.type==='wound'?['#fff1db','#d99175']:['#fff8df','#f0c77c'];if(hit||broken){const count=broken?20:12;for(let j=0;j<count;j++){let a=j*2.399963+(e.id?.length||0),vel=(broken?2.4:1.5)+(j%3)*.35,y=1.25+Math.cos(a)*age*vel-age*age*2;this.add(broken&&j%3===0?'rbox':'leaf',x+Math.sin(a)*age*vel,y,z+Math.cos(a*2)*age*vel,.045*(1-u)+.015,.24*(1-u)+.035,.034,palette[j%2],a,a*2+age*5,age*3,j%3===0?9:4,1-u,this.fxBatches);}
 if(age<.22){this.add('star',x,1.48,z,.86*(1-u),.95*(1-u),.06,broken?'#eeb271':'#f4ce80',this.camera.yaw,.11,-this.camera.pitch,4,(1-u)*.9,this.impactFX);this.add('star',x,1.48,z,.48*(1-u),.59*(1-u),.07,'#fff9df',this.camera.yaw,-.13,-this.camera.pitch,4,1-u,this.impactFX);}
 this.add('ring:6.283185307179586',x,.30,z,.4+age*2.2,1,.4+age*2.2,broken?'#d5a367':'#ede0b3',0,0,0,4,(1-u)*.55,this.fxBatches);
 if(broken&&e.severed){this.add('softbox',x+age*1.4,.6+Math.sin(u*Math.PI)*1.1,z-age*.6,.3,.55,.3,'#b1a289',age*3,age*5,age*2,0,1-u*.6,this.fxBatches);}}
 }
 }
 render(snapshot,dt=.016,options={}){if(this.lost||!snapshot)return;this.resize();const gl=this.gl,t=snapshot.t||0,p=snapshot.player||snapshot.players?.[0],area=snapshot.room?.kind||'village';let key=options.portrait?'portrait':options.clan?'showcase':area==='village'?'village'+snapshot.map.seed:'front'+Math.floor(-(p?.z||0)/44);if(key!==this.sceneKey){this.sceneKey=key;this.static.clear();if(options.portrait){this.groundFX.clear();this.labels=[];}else if(options.clan)this.art.showcase();else if(area==='village')this.art.village(snapshot.map);else this.art.front(snapshot.map.seed,Math.floor(-(p?.z||0)/44));this.staticShadowDirty=true;}
 if(options.clan&&options.preview){const c=options.preview;this.camera.x+=(c.x-this.camera.x)*Math.min(1,dt*8);this.camera.z+=(c.z-this.camera.z)*Math.min(1,dt*8);this.camera.zoom+=(4.2-this.camera.zoom)*Math.min(1,dt*8);this.camera.yaw=.12;this.camera.pitch=.24;}
 else if(p&&!options.freezeCamera){const foe=snapshot.actors?.find(e=>e.id===p.autoFight&&e.alive);if(foe&&this.combatTarget!==foe.id){const axis=Math.atan2(foe.x-p.x,foe.z-p.z),wrap=n=>Math.atan2(Math.sin(n),Math.cos(n)),a=axis+Math.PI/2,b=axis-Math.PI/2;this.combatYaw=Math.abs(wrap(a-this.camera.yaw))<Math.abs(wrap(b-this.camera.yaw))?a:b;this.combatTarget=foe.id;}if(!foe)this.combatTarget=null;const yaw=options.yaw??(foe?this.combatYaw:.42),cx=p.x+(foe?(foe.x-p.x)*.35:0),cz=p.z+(foe?(foe.z-p.z)*.35-1:-1.5);this.camera.x+=(cx-this.camera.x)*Math.min(1,dt*6);this.camera.z+=(cz-this.camera.z)*Math.min(1,dt*6);this.camera.zoom+=((foe?13.5:16)+(options.zoomOffset||0)-this.camera.zoom)*Math.min(1,dt*3);const dy=Math.atan2(Math.sin(yaw-this.camera.yaw),Math.cos(yaw-this.camera.yaw));this.camera.yaw+=dy*Math.min(1,dt*3);this.camera.pitch+=(.68-this.camera.pitch)*Math.min(1,dt*4);}
 this.matrix();this.stats={calls:0,triangles:0,instances:0,lodInstances:0,resolution:this.canvas.width+'×'+this.canvas.height,scale:this.scale,meshTypes:this.geo.size};this.dynamic.clear();this.fxBatches.clear();this.impactFX.clear();
 let entities=[...snapshot.actors||[],...snapshot.players||[]];if(p&&!entities.some(e=>e.id===p.id))entities.push(p);if(options.clan&&options.preview)entities=[options.preview];entities.sort((a,b)=>(a.id===p?.id)-(b.id===p?.id));
 for(const e of entities){if(Math.hypot(e.x-this.camera.x,e.z-this.camera.z)>33)continue;const lod=Math.hypot(e.x-this.camera.x,e.z-this.camera.z)>18;this.art.low=lod;let et=t;this.art.doll(e,et,e.id===p?.id);this.art.statuses(e,t);if(e.id===p?.id)this.art.parentScene(e,t);}
 this.combatFX(snapshot,t);
 // Static buildings reuse their shadow map until the light's tracked region changes.
 if(Math.hypot(this.camera.x-this.lastShadow[0],this.camera.z-this.lastShadow[1])>1.7){this.staticShadowDirty=true;}
 if(this.quality!=='low'){
  if(this.staticShadowDirty){this.shadowVP=new Float32Array(this.lightVP);this.lastShadow=[this.camera.x,this.camera.z];this.drawShadow(this.shadowStatic,this.static);this.staticShadowDirty=false;}else this.lightVP=this.shadowVP;
  this.drawShadow(this.shadowDynamic,this.dynamic);
 }
 gl.bindFramebuffer(gl.FRAMEBUFFER,this.target.fb);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.drawBuffers([gl.COLOR_ATTACHMENT0,gl.COLOR_ATTACHMENT1]);gl.clearColor(.93,.90,.82,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.depthMask(true);gl.disable(gl.CULL_FACE);gl.disable(gl.BLEND);gl.useProgram(this.program);this.uniform(this.program,'vp',this.vp);this.uniform(this.program,'lightVP',this.lightVP);this.uniform(this.program,'eye',this.eye);this.uniform(this.program,'focus',[this.camera.x,this.camera.z]);this.uniform(this.program,'time',t);this.int(this.program,'shadows',this.quality!=='low'?1:0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.shadowStatic.tex);this.int(this.program,'shadowTex',0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.shadowDynamic.tex);this.int(this.program,'dynamicShadow',1);
 this.drawBatches(this.static,this.program);this.drawBatches(this.dynamic,this.program);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);this.drawBatches(this.groundFX,this.program);this.drawBatches(this.fxBatches,this.program);gl.disable(gl.DEPTH_TEST);this.drawBatches(this.impactFX,this.program);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.disable(gl.BLEND);
 gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.disable(gl.DEPTH_TEST);gl.useProgram(this.post);gl.bindVertexArray(null);for(const [i,name,tex]of [[0,'image',this.target.image],[1,'depth',this.target.depth],[2,'normals',this.target.normals]]){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,tex);this.int(this.post,name,i);}this.uniform(this.post,'texel',[1/this.canvas.width,1/this.canvas.height]);this.uniform(this.post,'occlusion',this.quality==='low'?0:1);this.uniform(this.post,'portrait',options.portrait?2:options.clan?1:0);gl.drawArrays(gl.TRIANGLES,0,3);this.stats.calls++;this.frame++;
 if(this.quality==='auto'&&this.frame>120&&!options.clan){this.frameMs=this.frameMs*.98+Math.min(dt*1000,120)*.02;this.stableFrames++;if(this.stableFrames>180){if(this.frameMs>29&&this.scale>.70){this.scale=Math.max(.70,this.scale-.10);this.lastSize='';}else if(this.frameMs<20&&this.scale<1){this.scale=Math.min(1,this.scale+.05);this.lastSize='';}this.stableFrames=0;}}
 }
 drawShadow(target,map){const gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,target.fb);gl.viewport(0,0,target.size,target.size);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);gl.disable(gl.BLEND);gl.disable(gl.CULL_FACE);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1.2,2.0);gl.clearDepth(1);gl.clear(gl.DEPTH_BUFFER_BIT);gl.useProgram(this.depthProgram);this.uniform(this.depthProgram,'vp',this.lightVP);this.uniform(this.depthProgram,'lightVP',this.lightVP);this.drawBatches(map,this.depthProgram,true);gl.disable(gl.POLYGON_OFFSET_FILL);}
}


