

const ESC=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const UI_PATH={leaf:'M12 21V8m0 7C3 15 2 9 3 5c7 0 9 3 9 10Zm0-5c0-6 5-8 9-8 1 6-3 9-9 9',sword:'m4 20 3-3m-3-3 6 6M8 16l11-13 2 1-1 4L11 18',bag:'M8 3h8l-2 5c6 2 7 6 6 11-3 3-13 3-16 0-1-5 0-9 6-11Zm1 5h6m-9 6h12',book:'M12 5C8 2 3 3 2 4v16c4-2 7-1 10 1m0-16c4-3 9-2 10-1v16c-4-2-7-1-10 1Zm0 0v16',home:'m2 11 10-8 10 8M5 9v12h5v-7h4v7h5V9',menu:'M4 6h16M4 12h16M4 18h16',close:'m5 5 14 14M5 19 19 5',back:'m14 4-8 8 8 8M6 12h15',shield:'m12 2 8 4-1 10-7 6-7-6L4 6Zm0 4v12',rest:'M11 4a2 2 0 1 0 0 .1M10 9l-1 6 7 0 3 6M9 15l-4 5h8M9 10l5 2 3-3',hand:'M7 21 3 12q1-2 3 0l2 2V5q2-2 3 0v7-9q2-1 3 1v8-8q2-1 3 1v8-5q3-1 3 2v8l-4 3Z',helm:'M4 15V9a8 8 0 0 1 16 0v6l-5 6h-6Zm0-3 7 3v6m9-9-7 3v6',arrow:'m8 4 8 8-8 8',sound:'M3 9h4l5-5v16l-5-5H3Zm13-2q6 5 0 10m-1-7q2 2 0 4',fire:'M12 2c3 7-4 6 1 11 3-1 4-4 4-4 9 10-2 17-9 11-6-5 0-12 4-18Z',star:'m12 2 3 7 7 1-5 5 1 7-6-4-6 4 1-7-5-5 7-1Z',boat:'M4 16 12 20l8-4-3 6H7Zm8-13v12M10 5 3 13h7m4-8 7 8h-7',heart:'M12 21C-6 9 5-3 12 6 19-3 30 9 12 21Z',hammer:'m4 21 9-12m-4-5 4-3 8 8-4 4Z'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.45" stroke-linecap="round" stroke-linejoin="round"><path d="${UI_PATH[name]||UI_PATH.star}"/></svg>`;
const schoolIcon=s=>({unarmed:'hand',heavy:'hammer',light:'feather',shield:'shield',blade:'sword',magic:'star',church:'sun',occult:'moon',sword:'sword'})[s]||'sword';
const label=(text,cls='')=>typeof GAME_LABELS!=='undefined'&&GAME_LABELS[text]?`<img class="ink-label ${cls}" alt="${ESC(text)}" src="${GAME_LABELS[text]}">`:`<span class="${cls}">${ESC(text)}</span>`;

Object.assign(UI_PATH,{
 talk:'M4 3h16q3 0 3 3v10q0 3-3 3H11l-6 4v-4H4q-3 0-3-3V6q0-3 3-3Zm3 7h.1m5 0h.1m5 0h.1',
 map:'m2 5 6-3 8 3 6-3v17l-6 3-8-3-6 3Zm6-3v17m8-14v17',
 bell:'M12 2v2m-7 12 2-3V9a5 5 0 0 1 10 0v4l2 3Zm-4 3q-3 4-6 0',
 stone:'m3 17 2-10 9-4 7 8-2 8-10 2Zm2-10 8 5 6 7m-6-7-4 9',
 feather:'M4 21 17 5M6 15C-2 5 15 0 21 2c0 9-5 19-15 13Zm4-6 1 7m4-11 1 5',
 net:'M3 3h18v18H3Zm0 6h18M3 15h18M9 3v18m6-18v18',
 sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M17 12a5 5 0 1 1-10 0 5 5 0 1 1 10 0',
 moon:'M19 17A9 9 0 0 1 9 3a10 10 0 1 0 10 14Z',
 spark:'M12 2 14 10 22 12 14 14 12 22 10 14 2 12 10 10Z',
 cloth:'m8 3 4 3 4-3 6 5-4 5-2-2v11H8V11l-2 2-4-5Z',
 boot:'M6 3h9v10l5 3q3 5-2 6H4V11Zm-2 15h17',
 eye:'M2 12q10-14 20 0-10 14-20 0Zm14 0a4 4 0 1 1-8 0 4 4 0 1 1 8 0'
});
const costMarks=s=>`<span class="cost-marks" role="img" aria-label="消耗 ${staminaTier(s)}段階">${Array.from({length:5},(_,i)=>`<i class="${i<staminaTier(s)?'lit':''}"></i>`).join('')}</span>`;
const schoolName=s=>({unarmed:'体術',blade:'剣技',heavy:'剛技',light:'軽業',shield:'盾術',magic:'魔術',church:'信仰',occult:'禁術'})[s]||'武術';
const itemIcon=id=>icon(ITEMS[id]?.icon||'bag');
function anatomy(p,large=false){const color=part=>({light:'#d2ae61',heavy:'#ce7459',lost:'#484340'})[p.wounds?.[part]?.severity]||'#b4c7a2';return `<svg class="anatomy ${large?'large':''}" viewBox="0 0 58 96" role="img" aria-label="部位の傷"><g stroke="#ebdfbb" stroke-width="1.15"><circle data-part="head" cx="29" cy="12" r="9" fill="${color('head')}"/><path data-part="torso" d="M20 25q9-5 18 0l1 30q-10 7-20 0Z" fill="${color('torso')}"/><path data-part="rightArm" d="m17 26-7 2-6 29q0 6 6 4l10-26" fill="${color('rightArm')}"/><path data-part="leftArm" d="m41 26 7 2 6 29q0 6-6 4L38 35" fill="${color('leftArm')}"/><path data-part="rightLeg" d="m20 57-3 31q0 8 9 4l3-33" fill="${color('rightLeg')}"/><path data-part="leftLeg" d="m38 57 3 31q0 8-9 4l-3-33" fill="${color('leftLeg')}"/></g></svg>`;}
function orb(){return `<div class="stamina-orb" role="img" aria-label="息に余裕がある"><svg viewBox="0 0 72 96"><defs><linearGradient id="gold" x2=".8" y2="1"><stop stop-color="#f3dda8"/><stop offset=".36" stop-color="#a3844f"/><stop offset=".56" stop-color="#e4c897"/><stop offset="1" stop-color="#806039"/></linearGradient><radialGradient id="glass" cx=".4" cy=".3"><stop stop-color="#314733"/><stop offset="1" stop-color="#1c302c"/></radialGradient><linearGradient id="water" x2=".1" y2="1"><stop stop-color="#c7eeae"/><stop offset=".23" stop-color="#8fc789"/><stop offset=".6" stop-color="#538e6b"/><stop offset="1" stop-color="#285d50"/></linearGradient><clipPath id="orb-clip"><ellipse cx="36" cy="44" rx="22.8" ry="31"/></clipPath><radialGradient id="orbshine"><stop stop-color="#effada" stop-opacity=".35"/><stop offset="1" stop-color="#effada" stop-opacity="0"/></radialGradient></defs><path d="M36 3q-5 9-13 12C3 22 2 66 24 78q8 4 12 13 4-9 12-13C70 66 69 22 49 15Q41 12 36 3Z" fill="#685c43" stroke="url(#gold)" stroke-width="1.7"/><ellipse cx="36" cy="44" rx="26" ry="35" fill="none" stroke="url(#gold)" stroke-width="2.5"/><ellipse cx="36" cy="44" rx="23" ry="31.5" fill="url(#glass)"/><g clip-path="url(#orb-clip)"><path id="orb-cap" fill="#2c3027" opacity=".75"/><path id="orb-water" fill="url(#water)"/><path id="orb-wave" fill="none" stroke="#e8f7c8" stroke-width="1.1"/><ellipse cx="29" cy="30" rx="15" ry="23" fill="url(#orbshine)"/><circle cx="27" cy="56" r="1.3" fill="#edfadd" opacity=".62"/><circle cx="39" cy="64" r="1.8" fill="#bde4a8" opacity=".4"/><circle cx="45" cy="43" r=".8" fill="#f4ffdd" opacity=".7"/></g><path d="M18 39q1-18 12-22" stroke="#fff5da" stroke-width="2.3" stroke-linecap="round" opacity=".73" fill="none"/><path d="M48 56q-2 13-10 15" stroke="#e1efd4" opacity=".28" stroke-width="1" fill="none"/><g fill="#789269" stroke="#b9ba85" stroke-width=".7"><path d="M23 76Q8 79 8 66 19 63 23 76Z"/><path d="M16 67Q3 65 6 55 15 56 16 67Z"/><path d="M49 76q15 3 15-10-11-3-15 10Z"/><path d="M56 67q13-2 10-12-9 1-10 12Z"/></g><path d="m36 8 3 5-3 4-3-4Zm0 71 4 6-4 6-4-6Z" fill="#acbb80" stroke="#e4c997"/><path d="M29 8Q36-1 43 8M30 89q6 6 12 0" fill="none" stroke="url(#gold)" stroke-width="1.5"/></svg></div>`;}
class UI {
 constructor(game){this.g=game;this.modal=null;this.phase=0;this.detail=null;this.clan=document.getElementById('clan-screen');this.hud=document.getElementById('hud');this.root=document.getElementById('modal-root');this.lastSkills='';this.lastContext='';this.deathShown='';this.portraits=new Map();this.portraitQueue=[];this.floatLines=[];this.pieDragging=false;this.hudPortrait='';}
 toast(text){const n=document.createElement('div');n.className='toast';n.textContent=text;const box=document.getElementById('toasts');box.appendChild(n);while(box.children.length>2)box.firstChild.remove();setTimeout(()=>n.remove(),3800);}
 showClan(){SkillPresentation.clear(this);this.closeModal();this.hud.classList.add('hidden');document.getElementById('world-labels').innerHTML='';this.clan.classList.remove('hidden');this.renderClan();}
 renderClan(){const p=this.g.profile;this.clan.innerHTML=`<div class="clan-heading"><div class="crest">${icon('leaf')}</div><div class="wordmark">CHRONICLES OF THE HEARTH</div>${label(GAME_TITLE,'title-ink')}<p>この灯を、次の命へ。</p></div><div class="clan-bottom"><div class="blood-options">${RACES.map((r,i)=>`<button class="blood ${p.race===i?'chosen':''}" data-race="${i}" aria-pressed="${p.race===i}"><span class="blood-glyph blood-${i}">${['人','森','山','狐'][i]}</span>${label(r.name)}</button>`).join('')}</div><p class="blood-description">${RACES[p.race]?.desc||''}</p><div class="name-row"><label>名<input id="life-name" maxlength="12" placeholder="風にまかせる" value="${ESC(p.name)}"></label><button id="clan-lineage" class="quiet-button">${icon('book')}系譜</button><button id="clan-settings" class="quiet-button" aria-label="設定">${icon('menu')}</button></div><button class="begin-button" id="begin-life">${label(this.g.canResume()?'旅を続ける':'この血に生まれる')}${icon('arrow')}</button><div class="version">${p.online?'共有の村':'ひとりの村'} · v${VERSION}</div></div>`;
  this.clan.querySelectorAll('[data-race]').forEach(b=>b.onclick=()=>{p.race=+b.dataset.race;this.g.previewCharacter.race=p.race;this.g.saveProfile();this.renderClan();});document.getElementById('life-name').oninput=e=>{p.name=e.target.value;this.g.saveProfile();};document.getElementById('begin-life').onclick=()=>this.g.start();document.getElementById('clan-lineage').onclick=()=>this.lineage();document.getElementById('clan-settings').onclick=()=>this.settings();
 }
 showGame(){this.lastContext=null;this.hudPortrait='';this.clan.classList.add('hidden');this.hud.classList.remove('hidden');this.hud.innerHTML=`<div class="player-mark"><div class="portrait-frame" id="hud-portrait">${icon('leaf')}</div><div class="player-info"><strong id="player-name"></strong><div class="life-line"><span id="age"></span><span id="condition"></span></div></div></div><button class="wound-mark" id="wound-mark" aria-label="傷のある部位"></button><div class="orb-wrap">${orb()}</div><div class="place-mark"><div class="day-line">${icon('sun')}<span id="day"></span></div><span id="place"></span></div><button class="mini-map" id="mini-map" aria-label="地図"><canvas id="map-preview" width="200" height="200"></canvas><i>${icon('map')}</i></button><div class="hud-bottom"><button data-menu="body" class="hud-button">${icon('bag')}${label('身支度')}</button><button data-menu="skills" class="hud-button">${icon('leaf')}${label('意識')}</button><button data-menu="map" class="hud-button">${icon('map')}${label('地図')}</button><button data-menu="settings" class="hud-button">${icon('menu')}${label('設定')}</button></div><div id="context" class="context"></div><button class="talk-button" id="talk-button" aria-label="話す">${icon('talk')}</button><div id="mother-dialogue"></div><div id="gift-tray"></div>`;
  this.hud.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>this[b.dataset.menu]());document.getElementById('talk-button').onclick=()=>this.talk();document.getElementById('mini-map').onclick=()=>this.map();document.getElementById('wound-mark').onclick=()=>this.wounds();this.deathShown='';
 }
 open(type,title,html){this.g.stopInput();this.pieDragging=false;this.portraitQueue=this.portraitQueue.filter(q=>q.node.id==='hud-portrait');this.modal=type;this.g.renderer.diorama.suspended=type==='lineage';this.root.className='modal-root visible '+type;this.root.innerHTML=`<section class="game-panel ${['body','lineage','onboarding','wounds'].includes(type)?'parchment':''}" role="dialog" aria-modal="true" aria-label="${ESC(title)}"><header class="panel-head"><button class="panel-back" aria-label="戻る">${icon('back')}</button><h2>${label(title)}</h2><span class="panel-flower">${icon('leaf')}</span></header><div class="panel-content">${html}</div></section>`;this.root.querySelector('.panel-back').onclick=()=>this.closeModal();}
 closeModal(){this.pieDragging=false;this.modal=null;this.g.renderer.diorama.suspended=false;this.detail=null;this.root.innerHTML='';this.root.className='modal-root';this.portraitQueue=this.portraitQueue.filter(q=>q.node?.isConnected);}
 onboarding(done,index=0){const pages=[
  {title:'歩む、休む',glyph:'hand',text:'地面をタップして、そこへ。<br>ドラッグで歩き、フリックで駆け続ける。<br>タップで止まり、長押しでひと休み。',note:'マウスも指も、同じ操作。'},
  {title:'身体の声',glyph:'heart',text:'左上に、年齢と体調。<br>小さな身体の色が、傷の場所。<br>緑のオーブは、残っている息。',note:'話すか歩くと、休息を終える。'},
  {title:'心の采配',glyph:'leaf',text:'敵に近づくと、覚えた技で戦う。<br>「序・破・急」の輪を動かして配分。<br>◆が多い技ほど、息を使う。',note:'支度のあいだも、世界は進む。'}
 ];const pg=pages[index];this.open('onboarding','旅の手ほどき',`<div class="guide-emblem">${icon(pg.glyph)}</div><h3 class="guide-title">${pg.title}</h3><p class="guide-text">${pg.text}</p><p class="guide-note">${pg.note}</p><div class="guide-pages">${pages.map((_,i)=>`<i class="${i===index?'on':''}"></i>`).join('')}</div><button id="guide-next" class="begin-button">${index===pages.length-1?'旅を始める':'次へ'}${icon('arrow')}</button>`);document.getElementById('guide-next').onclick=()=>{if(index<pages.length-1)this.onboarding(done,index+1);else{this.closeModal();done?.();}};this.root.querySelector('.panel-back').onclick=()=>{this.closeModal();done?.();};}
 skills(){this.phase=0;this.open('skills','心の采配','<div id="skills-content"></div>');this.renderSkills();SkillPresentation.opened(this);}
 renderSkills(){if(this.modal!=='skills')return;const p=this.g.snapshot?.player;if(!p)return;const ids=p.skills.filter(id=>skillPhase(skillById(id))===this.phase),weights=p.phaseWeights[this.phase]||{};this.lastSkills=JSON.stringify([ids,weights,p.weapon,p.inventory]);
  const colors=['#9aba8f','#d8b67c','#a8aec6','#c48d75','#86b4b0','#c7bb89','#bc9bba','#a7a286'];this.skillColors=Object.fromEntries(ids.map((id,i)=>[id,colors[i%colors.length]]));
  document.getElementById('skills-content').innerHTML=`<div class="phase-tabs">${PHASES.map((name,i)=>`<button data-phase="${i}" aria-selected="${this.phase===i}" class="${this.phase===i?'chosen':''}">${label(name)}</button>`).join('')}</div><div id="pie-wrap"></div><div id="pie-legend" class="pie-legend"></div><div class="skill-grid">${ids.length?ids.map(id=>{const sk=skillById(id),locked=skillRestriction(p,sk);return`<div class="skill-cell ${weights[id]>0?'enabled':''}" style="--ink:${this.skillColors[id]}"><button data-skill="${id}" class="skill-tile ${locked?'restricted':''}" aria-pressed="${weights[id]>0}" aria-label="${ESC(sk.name)}"><span class="skill-sigil">${icon(schoolIcon(sk.school))}</span><span class="skill-name">${ESC(sk.name)}</span>${costMarks(sk)}</button><button data-detail="${id}" class="detail-dot" aria-label="${ESC(sk.name)}の説明">·</button></div>`;}).join(''):'<div class="phase-empty">まだ、この段の技はない。</div>'}</div><div id="skill-detail" class="skill-detail"><span>技を選び、輪で配分。</span></div>${p.passives.length?`<div class="passive-row">${p.passives.map(id=>`<button data-passive="${id}" title="${ESC(skillById(id)?.name)}">${icon(schoolIcon(skillById(id)?.school))}<span>${ESC(skillById(id)?.name)}</span></button>`).join('')}</div>`:''}`;
  this.root.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{this.phase=+b.dataset.phase;this.renderSkills();});
  this.root.querySelectorAll('[data-skill]').forEach(b=>{let hold=null,start=null,suppressed=false;const id=+b.dataset.skill;
   b.onpointerdown=e=>{start={x:e.clientX,y:e.clientY};suppressed=false;hold=setTimeout(()=>{suppressed=true;this.describeSkill(id);},470);};
   b.onpointermove=e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>9){clearTimeout(hold);suppressed=true;}};
   b.onpointerup=b.onpointercancel=()=>clearTimeout(hold);b.oncontextmenu=e=>e.preventDefault();
   b.onclick=()=>{if(suppressed)return;const w={...this.g.snapshot.player.phaseWeights[this.phase]};w[id]=w[id]>0?0:20;this.g.command({type:'weights',phase:this.phase,weights:w});this.renderSkills();};
   b.onkeydown=e=>{if(e.shiftKey&&e.key==='F10'){e.preventDefault();this.describeSkill(id);}};
  });
  this.root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>this.describeSkill(+b.dataset.detail));this.root.querySelectorAll('[data-passive]').forEach(b=>b.onclick=()=>this.describeSkill(+b.dataset.passive));this.drawPie(ids,weights);SkillPresentation.rendered(this);
 }
 shortDescription(sk){if(sk.miracle||sk.occult||sk.items||sk.passive)return sk.desc;return (sk.desc||'隙を突く。').split('。')[0].slice(0,29)+'。';}
 describeSkill(id){if(SkillPresentation.describe(this,id))return;const sk=skillById(id);if(!sk)return;const el=document.getElementById('skill-detail');if(!el)return;el.innerHTML=`<strong>${ESC(sk.name)}</strong><span>${ESC(this.shortDescription(sk))}</span>${sk.passive?'':costMarks(sk)}${sk.items?`<small>${sk.items.map(i=>ESC(ITEMS[i].name)).join(' ＋ ')}</small>`:''}`;}
 pieMarkup(ids,weights){const entries=ids.filter(id=>weights[id]>0),sum=entries.reduce((n,id)=>n+weights[id],0);this.pieEntries=entries;this.pieAngles=[];let end=-Math.PI/2,paths='',handles='',marks='';const pos=(a,r=67)=>[104+Math.cos(a)*r,100+Math.sin(a)*r];
  const exact=entries.map(id=>weights[id]/sum*100),pct=exact.map(Math.floor);let left=100-pct.reduce((a,b)=>a+b,0);const rem=exact.map((v,i)=>({i,r:v-pct[i]})).sort((a,b)=>b.r-a.r);for(let n=0;n<left&&rem.length;n++)pct[rem[n%rem.length].i]++;
  for(let i=0;i<entries.length;i++){const start=end,delta=weights[entries[i]]/sum*TAU;end+=delta;const a=pos(start),b=pos(end),c=pos((start+end)/2,49),color=this.skillColors[entries[i]];paths+=entries.length===1?`<circle cx="104" cy="100" r="67" fill="${color}"/>`:`<path d="M104 100 L${a[0]} ${a[1]} A67 67 0 ${delta>Math.PI?1:0} 1 ${b[0]} ${b[1]}Z" fill="${color}" stroke="#e8d7b3" stroke-width=".85"/>`;if(delta>.26)marks+=`<text class="pie-index" x="${c[0]}" y="${c[1]+4}" text-anchor="middle">${ids.indexOf(entries[i])+1}</text>`;this.pieAngles.push(end);if(entries.length>1&&i<entries.length-1)handles+=`<g class="pie-handle" data-handle="${i}" role="slider" aria-label="${ESC(skillById(entries[i]).name)}の配分" aria-valuemin="1" aria-valuemax="99" aria-valuenow="${pct[i]}" tabindex="0"><circle cx="${b[0]}" cy="${b[1]}" r="15" fill="transparent"/><path class="handle-diamond" d="M${b[0]} ${b[1]-6}l6 6-6 6-6-6Z" fill="#f4e0a7" stroke="#796548" stroke-width="1.2"/></g>`;}
  const legend=entries.length?entries.map((id,i)=>`<div data-ratio="${id}"><i style="background:${this.skillColors[id]}">${ids.indexOf(id)+1}</i><span>${ESC(skillById(id).name)}</span><b>${pct[i]}<small>%</small></b></div>`).join(''):'<span class="empty-ratio">採用する技を選ぼう</span>';
  return {svg:`<circle cx="104" cy="100" r="89" fill="none" stroke="#c6b18a" stroke-width=".65"/><circle cx="104" cy="100" r="78" fill="none" stroke="#c6b18a" stroke-width=".35"/><circle cx="104" cy="100" r="71" fill="#343a31" stroke="#d3bd90" stroke-width="1.5"/><g opacity=".84">${paths}</g><circle cx="104" cy="100" r="23" fill="#41473b" stroke="#d7c69a"/>${marks}<text x="104" y="108" class="pie-center" text-anchor="middle">${PHASES[this.phase]}</text>${handles}<path d="m104 3 4 6-4 7-4-7Z M104 184l4 6-4 7-4-7Z" fill="#d8c395"/>`,legend};
 }
 drawPie(ids,weights){const markup=this.pieMarkup(ids,weights),wrap=document.getElementById('pie-wrap');wrap.innerHTML=`<svg id="balance-pie" viewBox="0 0 208 200" aria-label="${PHASES[this.phase]}の技の配分">${markup.svg}</svg>`;document.getElementById('pie-legend').innerHTML=markup.legend;const svg=document.getElementById('balance-pie');let drag=null;
  const preview=w=>{const m=this.pieMarkup(ids,w);svg.innerHTML=m.svg;document.getElementById('pie-legend').innerHTML=m.legend;};
  svg.onpointerdown=e=>{const h=e.target.closest('[data-handle]');if(!h||this.pieEntries.length<2)return;e.preventDefault();const entries=[...this.pieEntries],sum=entries.reduce((n,id)=>n+weights[id],0),vals=entries.map(id=>weights[id]/sum),index=+h.dataset.handle;drag={entries,index,vals,before:vals.slice(0,index).reduce((a,b)=>a+b,0),initial:{...weights},pid:e.pointerId};this.pieDragging=true;svg.setPointerCapture(e.pointerId);};
  svg.onpointermove=e=>{if(!drag||e.pointerId!==drag.pid)return;e.preventDefault();const r=svg.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*208,y=(e.clientY-r.top)/r.height*200,a=(Math.atan2(y-100,x-104)+Math.PI/2+TAU)%TAU/TAU,both=drag.vals[drag.index]+drag.vals[drag.index+1],minimum=Math.min(.005,both*.1),v=clamp(a-drag.before,minimum,both-minimum),w={...drag.initial};drag.entries.forEach((id,i)=>w[id]=(i===drag.index?v:i===drag.index+1?both-v:drag.vals[i])*100);drag.pending=w;preview(w);};
  const finish=e=>{if(!drag||e.pointerId!==drag.pid)return;if(e.type==='pointerup'&&drag.pending)this.g.command({type:'weights',phase:this.phase,weights:drag.pending});drag=null;this.pieDragging=false;this.renderSkills();};svg.onpointerup=finish;svg.onpointercancel=finish;svg.onlostpointercapture=e=>{if(drag)finish({...e,type:'pointercancel',pointerId:e.pointerId});};
  svg.onkeydown=e=>{const h=e.target.closest('[data-handle]');if(!h||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const ent=this.pieEntries,i=+h.dataset.handle,sum=ent.reduce((n,id)=>n+weights[id],0),w=Object.fromEntries(ids.map(id=>[id,(weights[id]||0)/sum*100])),d=e.key==='ArrowRight'?1:-1,both=w[ent[i]]+w[ent[i+1]];w[ent[i]]=clamp(w[ent[i]]+d,.5,both-.5);w[ent[i+1]]=both-w[ent[i]];this.g.command({type:'weights',phase:this.phase,weights:w});this.renderSkills();};
 }
 body(){const p=this.g.snapshot?.player;if(!p)return;this.open('body','身支度',`<div class="wardrobe"><div class="wardrobe-figure" id="wardrobe-figure"></div><div class="equipped-list"><div>${icon(p.weapon<0?'hand':'sword')}<span>${p.weapon<0?'素手':ESC(WEAPONS[p.weapon]?.name)}</span></div><div>${icon(p.armor===0?'cloth':'helm')}<span>${ESC(ARMORS[p.armor]?.name)}</span></div><div>${icon(p.shield?'shield':'hand')}<span>${p.shield?'木鉄の盾':'左手は空き'}</span></div></div></div><h3 class="section-label">手荷物</h3><div class="inventory two-slots">${[0,1].map(i=>{const id=p.inventory[i];return `<div class="inventory-slot ${id?'filled':''}">${id?`${itemIcon(id)}<strong>${ESC(ITEMS[id].name)}</strong><span>${ESC(ITEMS[id].desc)}</span><button data-discard="${i}" aria-label="${ESC(ITEMS[id].name)}を手放す">手放す</button>`:`${icon('bag')}<span>空いている</span>`}</div>`;}).join('')}</div>${p.inventory.length===2&&p.passives.includes(4060)?`<div class="affinity-note">${icon('spark')}${itemAffinity(p).some(s=>s.items.length===2)?'ふたつの理が、響き合う。':'ふたつの品を、見比べる。'}</div>`:''}<button class="full-button" id="open-rack">${icon('sword')}武具棚で着替える${icon('arrow')}</button>`);this.queuePortrait(p,document.getElementById('wardrobe-figure'),'wardrobe');document.getElementById('open-rack').onclick=()=>this.rack();this.root.querySelectorAll('[data-discard]').forEach(b=>b.onclick=()=>{this.g.command({type:'discard',slot:+b.dataset.discard});this.body();});}
 wounds(){const p=this.g.snapshot?.player;if(!p)return;const hurt=Object.entries(p.wounds||{});this.open('wounds','身体の声',`<div class="wounds-figure">${anatomy(p,true)}</div><div class="wound-list">${hurt.length?hurt.map(([k,w])=>`<div><span>${BODY_NAMES[k]}</span><strong class="${w.severity}">${WOUND_NAMES[w.severity]}</strong></div>`).join(''):'<p>傷は、ない。</p>'}</div><div class="wound-key"><span>◆ 軽傷</span><span>◆ 重傷</span><span>◆ 欠損</span></div>`);}
 rack(){const p=this.g.snapshot?.player;if(!p)return;if(!this.g.nearRack()){this.toast('武器庫の棚へ近づこう');return;}const minor=p.age<EQUIP_AGE;this.lastGear=[p.weapon,p.armor,p.shield,minor].join(':');this.open('rack','武具棚',`<p class="rack-note">${minor?'武具は、七つになってから。':'手に馴染むものを。'}</p><h3>得物</h3><div class="gear-grid">${[{name:'素手',id:-1},...WEAPONS.map((w,i)=>({...w,id:i}))].map(w=>`<button data-slot="weapon" data-value="${w.id}" class="${p.weapon===w.id?'chosen':''}" ${minor?'disabled':''}>${icon(w.id<0?'hand':w.id===4?'hammer':'sword')}<span>${w.name}</span></button>`).join('')}</div><h3>身を包む</h3><div class="gear-grid">${ARMORS.map((a,i)=>`<button data-slot="armor" data-value="${i}" class="${p.armor===i?'chosen':''}" ${minor?'disabled':''}>${icon(i===0?'cloth':'helm')}<span>${a.name}</span></button>`).join('')}</div><h3>左手</h3><div class="gear-grid">${[false,true].map(a=>`<button data-slot="shield" data-value="${a}" class="${p.shield===a?'chosen':''}" ${minor?'disabled':''}>${icon(a?'shield':'hand')}<span>${a?'盾を持つ':'手を空ける'}</span></button>`).join('')}</div><p class="rack-school">今の学び · ${schoolName(gearSchool(p))}</p>`);this.root.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const value=b.dataset.slot==='shield'?b.dataset.value==='true':+b.dataset.value;if(this.g.command({type:'equip',slot:b.dataset.slot,value})){this.rack();}});}
 queuePortrait(p,node,suffix=''){const record={id:p.id,name:p.name,appearance:{...p,prologue:false},skills:[suffix==='hud'||suffix==='wardrobe'?null:p.currentSkill||4000],idle:suffix==='hud'||suffix==='wardrobe',head:suffix==='hud'},key=JSON.stringify([suffix,p.id,p.race,Math.floor(p.age/7),p.hair,p.weapon,p.armor,p.shield,p.skin]);if(this.portraits.has(key))node.innerHTML=`<img alt="${ESC(p.name)}の姿" src="${this.portraits.get(key)}">`;else this.portraitQueue.push({key,record,node});}
 lineage(){const l=this.g.getLegacy(),p=this.g.profile,records=[...(l.records||[])].reverse();this.open('lineage','血の系譜',`${!p.hideLineageHelp?`<div class="lineage-guide"><div>${icon('leaf')}</div><p>命を終えると、最も使った技が<br>ひとつ、系譜に刻まれる。</p><label><input id="hide-lineage-help" type="checkbox">次回から表示しない</label></div>`:''}<div class="lineage-list">${records.length?records.map((r,i)=>{const id=r.skills?.[0]??r.skill,sk=skillById(id);return `<button class="ancestor ${p.inherit?.includes(id)?'chosen':''}" data-ancestor="${id??''}" ${!sk?'disabled':''}><span class="ancestor-portrait" data-portrait="${i}"></span><span class="ancestor-meta"><small>第${r.gen||records.length-i}代</small><strong>${ESC(r.name||'名もなき旅人')}</strong><span>享年 ${Math.floor(r.age||0)}歳</span><b>${ESC(sk?.name||'技の記録なし')}</b></span><span class="ancestor-pick">${p.inherit?.includes(id)?'継':'›'}</span></button>`;}).join(''):'<p class="empty-lineage">白紙の頁に、最初の灯を。</p>'}</div><p class="lineage-note">受け継ぐのは、学びの癖。同じ技を覚える約束ではない。</p>`);const cb=document.getElementById('hide-lineage-help');if(cb)cb.onchange=()=>{p.hideLineageHelp=cb.checked;this.g.saveProfile();};this.root.querySelectorAll('[data-ancestor]').forEach(b=>b.onclick=()=>{const id=+b.dataset.ancestor;if(!l.archive.includes(id))return;p.inherit=p.inherit?.includes(id)?[]:[id];this.g.saveProfile();this.lineage();});records.forEach((r,i)=>{const key=(r.id||r.name)+':'+r.gen+':'+r.skills?.[0],node=this.root.querySelector(`[data-portrait="${i}"]`);if(this.portraits.has(key))node.innerHTML=`<img alt="${ESC(r.name)}の最期の姿" src="${this.portraits.get(key)}">`;else this.portraitQueue.push({key,record:r,node});});}
 talk(){this.g.stopInput();this.g.command({type:'talk'});const p=this.g.snapshot?.player;if(p?.prologue){this.open('chat','母の声',`<p class="chat-mother">${ESC(p.motherText).replaceAll('\n','<br>')}</p><button class="full-button" id="mother-more">もう少し教えて</button><button class="begin-button" id="mother-down">降ろして${icon('arrow')}</button>`);document.getElementById('mother-more').onclick=()=>this.talk();document.getElementById('mother-down').onclick=()=>{this.closeModal();this.g.command({type:'leaveIntro'});};return;}
  this.open('chat','声をかける',`<form id="chat-form"><input id="chat-text" maxlength="60" autocomplete="off" placeholder="声を、届ける"><button type="submit" class="full-button">${icon('talk')}話す</button></form><div class="chat-quick">${['ありがとう','よろしく','助けて'].map(x=>`<button data-say="${x}">${x}</button>`).join('')}</div>`);const say=text=>{if(this.g.command({type:'chat',text}))this.closeModal();};document.getElementById('chat-form').onsubmit=e=>{e.preventDefault();say(document.getElementById('chat-text').value);};this.root.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>say(b.dataset.say));}
 map(){this.open('map','村の地図','<canvas id="large-map" width="640" height="640"></canvas><div class="map-legend"><span>◆ 今いる場所</span><span>○ 学びの場所</span></div>');this.paintMap(document.getElementById('large-map'),this.g.snapshot,true);}
 paintMap(canvas,s,large=false){if(!canvas||!s)return;const ctx=canvas.getContext('2d'),w=canvas.width;ctx.clearRect(0,0,w,w);const isFront=s.room.kind==='front',map=s.map,cx=isFront?0:0,cz=isFront?-(s.room.stage*44+18):-7,range=large?42:30,point=(x,z)=>[w/2+(x-cx)*w/(range*2),w/2+(z-cz)*w/(range*2)];ctx.fillStyle='#d7d0a5';ctx.fillRect(0,0,w,w);ctx.strokeStyle='#ece0b7';ctx.lineWidth=w*.024;ctx.beginPath();const a=point(0,-48),b=point(0,30);ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();if(!isFront){for(const z of [7,-19]){ctx.beginPath();ctx.moveTo(...point(-32,z));ctx.lineTo(...point(32,z));ctx.stroke();}for(const h of map.houses){const [x,y]=point(h.x,h.z);ctx.fillStyle=['#9aa684','#af9a79','#899f9d','#b4977c'][h.id%4];ctx.fillRect(x-3,y-3,6,6);}for(const school of map.schools){const [x,y]=point(school.x,school.z);ctx.fillStyle=school.color;ctx.strokeStyle='#8b795b';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,large?8:5,0,TAU);ctx.fill();ctx.stroke();if(large){ctx.fillStyle='#4d4c36';ctx.font='18px serif';ctx.textAlign='center';ctx.fillText(school.short,x,y+25);}}}for(const a of s.actors.filter(a=>a.alive&&a.kind!=='dummy')){const [x,y]=point(a.x,a.z);ctx.fillStyle=a.kind==='guard'?'#798c9b':'#aa7964';ctx.beginPath();ctx.arc(x,y,large?3:2,0,TAU);ctx.fill();}const [x,y]=point(s.player.x,s.player.z);ctx.save();ctx.translate(x,y);ctx.rotate(-(s.player.dir||0)+Math.PI);ctx.fillStyle='#d6ead2';ctx.strokeStyle='#526f6b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(6,7);ctx.lineTo(0,4);ctx.lineTo(-6,7);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
 dioramaSettings(){
  const d=this.g.renderer.diorama;
  const row=(label,attribute,values,current)=>`<div class="setting-row"><span>${label}</span><div class="segments" role="group" aria-label="${label}">${values.map(([id,name])=>`<button ${attribute}="${id}" class="${current===id?'chosen':''}" aria-pressed="${current===id}">${name}</button>`).join('')}</div></div>`;
  return row('村の見え方','data-diorama-mode',[['normal','NORMAL'],['tilt-shift','TILT-SHIFT']],d.mode)+row('DOF','data-diorama-dof',[['off','OFF'],['subtle','SUBTLE'],['strong','STRONG']],d.dof);
 }
 settings(){const p=this.g.profile;this.open('settings','旅の支度',`<div class="setting-row"><span>${icon('sound')}音</span><button id="sound-toggle" class="pill">${p.sound?'響かせる':'静かに'}</button></div><div class="setting-row"><span>描画</span><div class="segments">${[['auto','自動'],['high','精細'],['medium','標準'],['low','軽量']].map(([id,n])=>`<button data-quality="${id}" class="${p.quality===id?'chosen':''}">${n}</button>`).join('')}</div></div>${this.dioramaSettings()}<button class="full-button" id="lineage-nav">${icon('book')}血の系譜${icon('arrow')}</button><button class="full-button" id="help-nav">${icon('hand')}操作の手ほどき${icon('arrow')}</button><button class="full-button" id="export-save">${icon('bag')}記録を持ち出す</button><label class="full-button import-label">${icon('book')}記録を読み込む<input type="file" id="import-save" accept="application/json,.json"></label><div class="settings-network"><label><input type="checkbox" id="online-mode" ${p.online?'checked':''}>共有の村へ</label><input class="room-code" id="room-code" placeholder="村の合言葉" value="${ESC(p.villageCode||'')}" maxlength="24"><small>${this.g.serverAvailable?'共有サーバーに接続済み':'共有は同梱サーバーから起動'}</small></div>${this.g.screen==='game'?'<button class="full-button" id="to-clan">一族へ戻る</button>':''}<div class="version">${GAME_TITLE} · VS-01</div>`);document.getElementById('sound-toggle').onclick=()=>{p.sound=!p.sound;p.sound?this.g.audio.enable():this.g.audio.disable();this.g.saveProfile();this.settings();};this.root.querySelectorAll('[data-quality]').forEach(b=>b.onclick=()=>{p.quality=b.dataset.quality;this.g.renderer.setQuality(p.quality);this.g.saveProfile();this.settings();});this.root.querySelectorAll('[data-diorama-mode]').forEach(b=>b.onclick=()=>{this.g.renderer.diorama.configure(b.dataset.dioramaMode);this.settings();});this.root.querySelectorAll('[data-diorama-dof]').forEach(b=>b.onclick=()=>{this.g.renderer.diorama.configure(undefined,b.dataset.dioramaDof);this.settings();});document.getElementById('lineage-nav').onclick=()=>this.lineage();document.getElementById('help-nav').onclick=()=>this.onboarding(()=>{});document.getElementById('export-save').onclick=()=>this.g.exportSave();document.getElementById('import-save').onchange=e=>this.g.importSave(e.target.files[0]);document.getElementById('online-mode').onchange=e=>{p.online=e.target.checked;this.g.saveProfile();};document.getElementById('room-code').onchange=e=>{p.villageCode=e.target.value;this.g.saveProfile();};const c=document.getElementById('to-clan');if(c)c.onclick=()=>this.g.toClan();}
 death(p){if(this.deathShown===p.id)return;this.deathShown=p.id;this.g.stopInput();setTimeout(()=>{if(this.g.snapshot?.player.id!==p.id||p.alive)return;const sk=skillById(p.bankedSkills?.[0]);this.open('death','命の灯',`<div class="death-leaf">${icon('leaf')}</div><h3 class="death-name">${ESC(p.name)}</h3><p class="death-age">享年 ${Math.floor(p.age)}歳</p><p>${sk?`「${ESC(sk.name)}」を、系譜に刻んだ。`:'静かな灯が、系譜に残った。'}</p><button id="next-life" class="begin-button">${label('次の命へ')}${icon('arrow')}</button><button class="full-button" id="view-lineage">系譜をひらく</button>`);document.getElementById('next-life').onclick=()=>this.g.toClan();document.getElementById('view-lineage').onclick=()=>this.lineage();},1600);}
 event(e){if(SkillPresentation.event(this,e))return;const own=e.player===this.g.playerId;if(['progress','speech','miracleQuiet','insight','passive'].includes(e.type)){const sk=skillById(e.id);this.floatLines.push({...e,born:this.g.snapshot?.t??e.t,text:e.type==='insight'?'閃き · '+sk?.name:e.type==='passive'?'心得 · '+sk?.name:e.text});this.floatLines=this.floatLines.slice(-16);}
  if(e.type==='released'&&own){this.g.resetPointer?.();this.g.walkTarget=null;}
  if(!own)return;if(e.type==='notice')this.toast(e.text);if(e.type==='pickup')this.toast(ITEMS[e.item]?.name+'を受け取った');if(e.type==='depart')this.toast('向こう岸へ');if(e.type==='returned')this.toast('ただいま');}
 update(s){if(this.g.screen!=='game'||!s?.player)return;const p=s.player,t=s.t,max=staminaMaximum(p),cap=clamp(p.staminaCap/max,0,1),fill=clamp(p.stamina/max,0,1);document.getElementById('player-name').textContent=p.name;document.getElementById('age').textContent=Math.floor(p.age)+'歳';const health=p.health??100,state=health<28?'危篤':health<60?'負傷':Object.values(p.statuses||{}).some(x=>x.until>t)?'不調':p.seated?'休息':p.stamina<15?'疲労':'良好',condition=document.getElementById('condition');condition.textContent=state;condition.style.color=health<28?'#f29a7d':health<60?'#eac077':state==='不調'?'#c7aad3':'#b4d6a0';
  const q=document.querySelector('.stamina-orb');q.setAttribute('aria-label',fill<.15?'息が切れそう':fill<.5?'息が浅くなってきた':'息に余裕がある');q.classList.toggle('tired',fill<.18);q.classList.toggle('recovering',!!p.seated);const y=75-fill*62,wave=Math.sin(t*1.6)*1.3;document.getElementById('orb-water').setAttribute('d',`M10 ${y}Q24 ${y-3+wave} 36 ${y}T62 ${y}V81H10Z`);document.getElementById('orb-wave').setAttribute('d',`M12 ${y}Q24 ${y-3+wave} 36 ${y}T60 ${y}`);document.getElementById('orb-cap').setAttribute('d',`M10 8H62V${75-cap*62}H10Z`);
  document.getElementById('place').textContent=s.room.kind==='front'?'最前線':p.z<-28?'村の外れ':s.room.name;document.getElementById('day').textContent='春の月 '+(Math.floor(t/120)%28+1)+'日';const woundsKey=JSON.stringify(p.wounds);if(woundsKey!==this.lastWounds){this.lastWounds=woundsKey;document.getElementById('wound-mark').innerHTML=anatomy(p);}const portraitKey=[p.id,Math.floor(p.age/7),p.race,p.armor,p.weapon,p.hair].join(':');if(portraitKey!==this.hudPortrait){this.hudPortrait=portraitKey;this.queuePortrait(p,document.getElementById('hud-portrait'),'hud');}
  this.paintMap(document.getElementById('map-preview'),s);if(this.modal==='map')this.paintMap(document.getElementById('large-map'),s,true);
  this.updateContext(s);this.updateMother(s);this.updateWorldLabels(s);SkillPresentation.update(this,s);
  if(this.modal==='skills'&&!this.pieDragging){const signature=JSON.stringify([p.skills.filter(id=>skillPhase(skillById(id))===this.phase),p.phaseWeights[this.phase]||{},p.weapon,p.inventory]);if(signature!==this.lastSkills)this.renderSkills();}if(this.modal==='rack'){const signature=[p.weapon,p.armor,p.shield,p.age<EQUIP_AGE].join(':');if(signature!==this.lastGear)this.rack();}if(!p.alive)this.death(p);
 }
 updateContext(s){const p=s.player,t=s.t,school=s.room.kind==='village'?s.map.schools.find(a=>Math.hypot(a.x-p.x,a.z-p.z)<a.r):null,item=s.room.items?.find(i=>i.ready<=t&&Math.hypot(i.x-p.x,i.z-p.z)<2.3),dummy=s.actors.find(a=>a.kind==='dummy'&&a.alive&&Math.hypot(a.x-p.x,a.z-p.z)<4),options=[];
  if(!p.prologue&&p.alive){if(this.g.nearRack())options.push({id:'rack',name:'武具棚',glyph:'sword'});if(school&&p.age>=4){const a=ACTIVITY_DEFS[school.id];if(a)options.push({id:'activity',value:a.id,name:p.activity===a.id?'やめる':a.label,glyph:p.activity===a.id?'close':a.id==='pray'?'sun':a.id==='observe'?'eye':a.id==='play'?'leaf':'book'});}if(dummy&&!p.activity)options.push({id:'practice',value:dummy.id,name:p.autoFight===dummy.id?'稽古をやめる':'人形と稽古',glyph:'sword'});if(item)options.push({id:'pickup',value:item.id,name:'拾う',glyph:'hand'});if(s.room.kind==='village'&&p.z>22)options.push({id:'boat',name:p.queued?'乗船をやめる':'舟に乗る',glyph:'boat'});if(s.room.kind==='front')options.push({id:'return',name:'帰り舟を呼ぶ',glyph:'boat'});}
  const signature=JSON.stringify(options);if(signature===this.lastContext)return;this.lastContext=signature;const node=document.getElementById('context');node.innerHTML=options.slice(0,3).map(o=>`<button data-context="${o.id}" data-value="${o.value||''}">${icon(o.glyph)}<span>${o.name}</span></button>`).join('');node.querySelectorAll('[data-context]').forEach(b=>b.onclick=()=>{const id=b.dataset.context;if(id==='rack'){this.rack();return;}this.g.stopInput();if(id==='activity')this.g.command({type:'activity',activity:b.dataset.value});if(id==='boat')this.g.command({type:'board'});if(id==='return')this.g.command({type:'return'});if(id==='pickup')this.g.command({type:'pickup',id:b.dataset.value});if(id==='practice'){const target=this.g.snapshot.actors.find(a=>a.id===b.dataset.value);if(!target)return;if(this.g.snapshot.player.autoFight===target.id){this.g.command({type:'sit',active:true});return;}this.g.command({type:'move',x:0,z:0});this.g.walkTarget={x:target.x,z:target.z,until:performance.now()+7000};}});
 }
 updateMother(s){const p=s.player,t=s.t,node=document.getElementById('mother-dialogue'),text=p.motherUntil>t?p.motherText:'';node.className=text?'mother-bubble':'hidden';if(text!==this.lastMother){this.lastMother=text;node.innerHTML=text?`<small>母</small><p>${ESC(text).replaceAll('\n','<br>')}</p>`:'';}if(text){const pos=this.g.renderer.project(p.prologue?p.x:p.introX,2.4,p.prologue?p.z:p.introZ);const ww=innerWidth,hh=innerHeight;node.style.left=clamp(pos.x,135,ww-135)+'px';node.style.top=clamp(pos.y-118,hh*.30,hh-290)+'px';}
  const giftKey=p.prologue?[p.inventory.join(','),p.giftOffer?.join(',')].join('|'):'none';if(giftKey!==this.lastGifts){this.lastGifts=giftKey;const tray=document.getElementById('gift-tray');tray.innerHTML=p.prologue?`<div class="gift-caption">手をのばす</div><div class="gift-buttons">${(p.giftOffer||[]).map(id=>`<button data-gift="${id}" ${p.inventory.length>=2?'disabled':''} aria-label="${ESC(ITEMS[id].name)}を受け取る">${itemIcon(id)}<span>${ESC(ITEMS[id].name)}</span></button>`).join('')}</div><button id="leave-arms">降ろして</button>`:'';tray.querySelectorAll('[data-gift]').forEach(b=>b.onclick=()=>this.g.command({type:'gift',item:b.dataset.gift}));const leave=document.getElementById('leave-arms');if(leave)leave.onclick=()=>this.g.command({type:'leaveIntro'});}
 }
 updateWorldLabels(s){const p=s.player,t=s.t,renderer=this.g.renderer,head=a=>((a.age??25)<10?2.2:3.15)*(a.race===2?.86:1),at=(a,h)=>renderer.project(a.x,h,a.z);let html='';for(const a of [...s.players,...s.actors]){if(!a.alive||Math.hypot(a.x-p.x,a.z-p.z)>13)continue;let pos=at(a,a.elite?4.3:head(a));if(!pos.visible)continue;
   if(a.combo&&a.kind==='player'){const band=clamp(a.combo.band,0,2),sk=skillById(a.pendingSkill?.id??a.attackSkill??a.currentSkill);html+=`<span class="combo-burst phase-${band}" style="left:${pos.x}px;top:${pos.y-15}px;--phase:${PHASE_COLORS[band]}">${PHASES[band]}</span>${sk?`<span class="skill-caption" style="left:${pos.x}px;top:${pos.y-54}px">${ESC(sk.name)}</span>`:''}`;}
   if(!['player','guard','dummy'].includes(a.kind))html+=`<div class="enemy-hp ${a.elite?'elite':''}" style="left:${pos.x}px;top:${pos.y}px"><i style="width:${clamp((a.hp??50)/(a.hpMax||50),0,1)*100}%"></i></div>`;
   if(a.speechUntil>t&&a.speech)html+=`<span class="speech-bubble" style="left:${clamp(pos.x,100,innerWidth-100)}px;top:${pos.y-43}px">${ESC(a.speech)}</span>`;
  }
  for(const b of renderer.labels){if(Math.hypot(b.x-p.x,b.z-p.z)>14)continue;const pos=renderer.project(b.x,b.y,b.z);if(pos.visible)html+=`<span class="building-label" style="left:${pos.x}px;top:${pos.y}px">${ESC(b.text)}</span>`;}
  this.floatLines=this.floatLines.filter(e=>t-e.born<4.6);for(const e of this.floatLines){const a=s.players.find(p=>p.id===e.player);if(!a||Math.hypot(a.x-p.x,a.z-p.z)>14||e.type==='speech')continue;const elapsed=t-e.born,pos=at(a,head(a)+.3);if(!pos.visible)continue;html+=`<span class="progress-float ${['insight','passive'].includes(e.type)?'discovery':''}" style="left:${clamp(pos.x,innerWidth*.3,innerWidth*.7)}px;top:${pos.y-elapsed*12}px;opacity:${Math.min(1,elapsed*3,(4.6-elapsed)*1.3)}">${ESC(e.text)}</span>`;}
  if(p.activity){const pos=at(p,head(p)+.02);html+=`<span class="activity-mark" style="left:${pos.x}px;top:${pos.y}px">${icon(p.activity==='pray'?'sun':p.activity==='play'?'leaf':'book')}</span>`;}
  document.getElementById('world-labels').innerHTML=html;
 }
}


