/* Layered, bounded ambience and positional foley. Reuses the original score and
 * event timing. Synthesized material-specific foley, not borrowed recordings. */
class WorldAudio extends AudioEngine{
 constructor(){super();this.panNodes=[];this.ambient=null;this.rainAmount=0;this.surface='grass';this.lastAmbient=-100;}
 initContext(c){super.initContext(c);const loop=(hz,kind)=>{const source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();source.buffer=this.noiseBuffer;source.loop=true;source.playbackRate.value=kind==='wind'?.37:kind==='fire'?.67:1;filter.type=kind==='rain'?'highpass':'lowpass';filter.frequency.value=hz;gain.gain.value=0;source.connect(filter);filter.connect(gain);gain.connect(this.master);source.start();return{source,filter,gain};};this.ambient={rain:loop(1700,'rain'),wind:loop(430,'wind'),fire:loop(280,'fire')};}
 setListener(p){super.setListener(p);if(!this.ctx||!p)return;const l=this.ctx.listener,c=this.ctx.currentTime;if(l.positionX){l.positionX.setValueAtTime(p.x,c);l.positionY.setValueAtTime(1.4,c);l.positionZ.setValueAtTime(p.z,c);l.forwardX.setValueAtTime(-.36,c);l.forwardY.setValueAtTime(-.55,c);l.forwardZ.setValueAtTime(-.76,c);}else l.setPosition(p.x,1.4,p.z);}
 updateWeather(w,s,sources){if(!w)return;this.rainAmount=w.rain;if(!this.enabled||!this.ambient||!s?.player)return;const c=this.ctx,t=c.currentTime;if(t-this.lastAmbient<.10)return;this.lastAmbient=t;this.ambient.rain.gain.gain.setTargetAtTime(w.rain*.095,t,.7);this.ambient.wind.gain.gain.setTargetAtTime(.009+w.wind*.010,t,.8);let fire=0;for(const a of sources||[])if(a.kind==='fire')fire=Math.max(fire,.055/(1+(Math.hypot(a.x-s.player.x,a.z-s.player.z)/3)**2));this.ambient.fire.gain.gain.setTargetAtTime(fire,t,.4);const p=s.player;this.surface=Math.abs(p.x)<2||Math.abs(p.z-7)<1.5||Math.abs(p.z+19)<1.5?'stone':'grass';this.panNodes=this.panNodes.filter(n=>{if(t>n.end){n.pan.disconnect();n.bus.disconnect();return false;}return true;});}
 fx(event){const e=typeof event==='string'?{type:event}:event;if(!e||!this.enabled||!this.ctx)return false;const old=this.fxBus,c=this.ctx;
  if(Number.isFinite(e.x)&&Number.isFinite(e.z)&&this.panNodes.length<24){const pan=c.createPanner(),bus=c.createGain();pan.panningModel='equalpower';pan.distanceModel='inverse';pan.refDistance=5;pan.maxDistance=35;pan.rolloffFactor=.28;pan.positionX.value=e.x;pan.positionY.value=e.type==='step'?.15:1.2;pan.positionZ.value=e.z;bus.connect(pan);pan.connect(old);this.fxBus=bus;this.panNodes.push({pan,bus,end:c.currentTime+2.2});}
  let played=false;try{if(e.type==='step'&&this.listener){const t=c.currentTime;if(t-(this.lastFX.get('step')??-100)>=.11){if(this.rainAmount>.35){this.noise(t,.085,.17,1450,.45);this.noise(t+.008,.13,.11,430,.6);}else if(this.surface==='stone'){this.noise(t,.055,.15,720,1.1);this.tone(46,t,.065,.12,'sine',false,this.fxBus,32);}else this.noise(t,.075,.18,980,.43);this.lastFX.set('step',t);this.effectCount++;played=true;}}
   else if(['pickup','equip','discard'].includes(e.type)){const t=c.currentTime;this.noise(t,.07,.12,e.type==='equip'?1500:700,.75);this.tone(e.type==='equip'?82:76,t,.18,.05,'triangle',false,this.fxBus);played=true;}
   else played=SkillPresentation.sound(this,e)||super.fx(e);
  }finally{this.fxBus=old;}return played;
 }
}
